<?php
$source_categories['fake-news'] = array(
  
  '2nd Amendment Daily News' => 'secondamendmentdaily.com',
  '3CCorp.net',
  '100% Fed up' => '100percentfedup.com',
  '10News.one' => 'www.10news.one',
  '12minutos.com',
  '24 News' => 'us24news.com/',
  'A Voice for Men' => 'www.avoiceformen.com',
  'Action News 3',
  'Activist Mommy' => 'activistmommy.com',
  'AjuaNews.com',
  'Al Arabiya' => 'english.alarabiya.net',
  'Al Bawaba' => 'www.albawaba.com',
  'All News Pipeline' => 'allnewspipeline.com',
  'Alliance Defending Freedom' => 'www.adflegal.org',
  'Al Manar' => 'english.almanar.com.lb',
  'Al- Masdar News' => 'almasdarnews.com',
  'Alpha News' => 'alphanewsmn.com',
  'AltRight.com',
  'America Daily' => 'americadaily.com',
  'America Talks with David Zublick' => 'https://americatalks.com',
  'American Action News' => 'americanactionnews.com',
  'American College of Pediatricians' => 'www.acpeds.org',
  'American Conservative Media' => 'americanconservativemedia.com',
  'American Family Association' => 'www.afa.net',
  'American Freedom Fighters' => 'www.americasfreedomfighters.com',
  'American Journal Review' => 'www.americanjournalreview.com',
  'American Lookout' => 'americanlookout.com',
  'American Patriot Daily' => 'www.americanpatriotdaily.com',
  'American People Daily' => 'americanpeopledaily.com',
  'American Principles Project' => 'americanprinciplesproject.org',
  'American Renaissance Magazine' => 'www.amren.com',
  'American Society for the Defense of Tradition, Family, and Property' => 'www.tfp.org',
  'American Thinker' => 'www.americanthinker.com',
  'American Truth Today' => 'americantruthtoday.com',
  'American Web Media' => 'awm.com',
  'Americans Are Pissed' => 'americansarepissed.com',
  'Americans for Truth' => 'https://americansfortruth.com',
  'America’s News Source' => 'americasnewssource.com',
  'Amity Underground',
  'Analyzing America' => 'analyzingamerica.org',
  'Anonymous News' => 'www.anonews.co',
  'Antelope Valley Today' => 'antelopevalleytoday.com',
  'Arab News' => 'www.arabnews.com',
  'Archaeology World' => 'archaeology-world.com',
  'Association of American Physicians and Surgeons' => 'AAPSaapsonline.org',
  'Auburn Times' => 'auburntimes.com',
  'Backroom Buzz' => 'backroombuzz.com',
  'Baldwin Times' => 'baldwintimes.com',
  'Banned Information' => 'bannedinformation.com',
  'Bare Naked Islam' => 'www.barenakedislam.com',
  'Basnews Agency' => 'basnews.com',
  'BB4SP' => 'bb4sp.com',
  'Bbarta24' => 'en.bbarta24.net',
  'BDnews24.com',
  'Before It’s News' => 'beforeitsnews.com',
  'Beijing Review' => 'www.bjreview.com',
  'Benton Times' => 'bentontimes.com',
  'Best Daily News' => 'bestdailynews.info',
  'Big League Politics' => 'bigleaguepolitics.com',
  'BillionBibles.org' => 'http://www.billionbibles.org',
  'Bipartisan Report' => 'www.bipartisanreport.com',
  'BitChute' => 'bitchute.com',
  'Black Eye Politics' => 'https://blackeyepolitics.com',
  'Black Genocide' => 'www.blackgenocide.org',
  'Black News' => 'Blacknews.com',
  'Black Pigeon Speaks' => 'blackpigeonspeaks.com,
  ','Blingnews.com' => 'www.blingnews.com',
  'Blue Dot Daily' => 'www.bluedotdaily.com',
  'Blunt Force Truth' => 'bluntforcetruth.com',
  'Bongino' => 'Bongino.com',
  'Bossip' => 'bossip.com',
  'Breaking911' => 'breaking911.com',
  'Breaking Christian News' => 'breakingchristiannews.com',
  'Breaking First' => 'breakingfirst.com',
  'Breaking News 247' => 'Breakingnews247.net',
  'Breaking News House' => 'breakingnewshouse.com',
  'Breaking Wide' => 'breakingwide.com',
  'Breitbart' => 'www.breitbart.com',
  'Caixin Globa' => 'caixinglobal.com',
  'Caldron Pool' => 'caldronpool.com',
  'Canada Free Press' => 'canadafreepress.com',
  'Cap News' => 'cap-news.com',
  'CCTV International' => 'CCTV-9english.cctv.com',
  'Center for Immigration Studies' => 'www.trueactivist.com',
  'Center for Research of Radicalism and National Security' => 'researchantisemitism.ca',
  'Center for Security Policy' => 'www.centerforsecuritypolicy.org',
  'Central OC Times' => 'centraloctimes.com',
  'Cerno' => 'Cernovich.comcernovich.com',
  'Checkpoint Asia' => 'https://www.checkpointasia.net',
  'Chico Times' => 'chicotimes.com',
  'China Daily' => 'www.chinadaily.com',
  'China Global Television Network' => 'america.cgtn.com/',
  'Christian Action Network' => 'christianaction.org',
  'Church Militant' => 'www.churchmilitant.com',
  'Clarion Project' => 'clarionproject.org',
  'Clash Daily' => 'clashdaily.com',
  'Clover Chronicle' => 'https://clovechronicle.com',
  'CNS News' => 'www.cnsnews.com',
  'Coachella Today' => 'coachellatoday.com',
  'Coconino News' => 'coconinonews.com',
  'Competitive Enterprise Institute' => 'cei.org',
  'Concerned Women for America' => 'concernedwomen.org',
  'Conservapedia' => 'www.conservapedia.com',
  'Conservative Ammo' => 'conservativeammo.com/',
  'Conservative Buzz',
  'Conservative Byte' => 'conservativebyte.com',
  'Conservative Daily News' => 'www.conservativedailynews.com',
  'Conservative Daily Post' => 'conservativedailypost.com',
  'Conservative Firing Line' => 'conservativefiringline.com',
  'Conservative Free Press' => 'www.conservativefreepress.com',
  'Conservative Matrix' => 'conservativematrix.com',
  'Conservative Media' => 'conservativemedia.com',
  'Conservative Politics Today' => 'facebook.com/conservativepoliticstoday',
  'Conservative Post' => 'conservativepost.com',
  'Conservative Tribune' => 'www.westernjournal.com',
  'Conservatives Today' => 'conservativetoday.org',
  'Council for American-Islamic Relations CAIR' => 'www.cair.com',
  'Council for the National Interest' => 'www.councilforthenationalinterest.org',
  'Council of Conservative Citizens',
  'Daily Buzz Live' => 'dailybuzzlive.com',
  'Daily Headlines' => 'dailyheadlines.net',
  'Daily Mail' => 'www.dailymail.co.uk',
  'Daily Political Newswire' => 'dailypoliticalnewswire.com',
  'Daily Star UK' => 'www.dailystar.co.uk',
  'Daily Stormer' => 'dailystormer.name',
  'Daily Surge' => 'dailysurge.com',
  'DavidHarrisJr.com',
  'DC Alert',
  'DC Blue Dot' => 'www.dcbluedot.com',
  'DC Dirty Laundry' => 'dcdirtylaundry.com',
  'DC Gazette' => 'thedcgazette.com',
  'DEBKAfile' => 'www.debka.com',
  'Decatur Times' => 'decaturtimes.com',
  'Deep Left Field' => 'deepleftfield.info',
  'Defend Europa' => 'www.defendevropa.org',
  'Defiant America' => 'defiantamerica.com',
  'Democratic National Committee' => 'DNCdemocrats.org',
  'Deplorable Kel' => 'deplorablekel.com',
  'Discover the Networks' => 'www.discoverthenetworks.org',
  'DJHJ Media' => 'djhjmedia.com',
  'DNyuz' => 'dnyuz.com',
  'Eagle Rising' => 'eaglerising.com', 
  'East Alameda News' => 'eastalamedanews.com',
  'East Arizona News' => 'eastarizonanews.com',
  'East Central Alabama News' => 'ecalabamanews.com',
  'East Contra Costa News' => 'eastcontracostanews.com',
  'East Little Rock Times' => 'eastlittlerocktimes.com',
  'East San Diego News' => 'eastsandiegonews.com',
  'East SBV Times' => 'eastsbvtimes.com',
  'East SFV Today' => 'eastsfvtoday.com',
  'East Sierra News' => 'eastsierranews.com',
  'East Ventura News' => 'eastventuranews.com',
  'Emirates 24/7' => 'emirates247.com',
  'En-volve' => 'en-volve.com',
  'End the Fed' => 'endthefed.org',
  'Every Legal Vote' => 'everylegalvote.com',
  'Everytown for Gun Safety' => 'everytown.org/',
  'Evil.News',
  'Experience Awareness' => 'AbcBusinessNews.com',
  'Explain Life' => 'explainlife.com',
  'Exposing Government' => 'www.exposinggovernment.com',
  'Fact Checking Turkey' => 'factcheckingturkey.com',
  'Facts Wanted' => 'factswanted.com',
  'Family Research Council' => 'www.frc.org',
  'Family Survival Headlines' => 'familysurvivalheadlines.com',
  'Fars News',
  'Fash the Nation' => 'fashthenation.com',
  'Fayetteville Standard' => 'fayettevillestandard.com',
  'FBNewsCycle',
  'Femalista' => 'femalista.com',
  'Filming Cops' => 'filmingcops.com',
  'Flag & Cross' => 'flagandcross.com',
  'Flex Mag' => 'www.usafortrumponline.com',
  'Focus on the Family' => 'www.focusonthefamily.com',
  'Foreign Policy Initiative' => 'www.foreignpolicyi.org',
  'For the Right News' => 'fortherightnews.com',
  'Fort Smith Times' => 'fortsmithtimes.com',
  'Freedom News Report' => 'freedomnewsreport.com',
  'Freedom Outpost',
  'FreedomProject Media',
  'Free West Media' => 'freewestmedia.com',
  'Fresno Leader' => 'fresnoleader.com',
  'FrontPage Magazine' => 'www.frontpagemag.com',
  'Gadsden Today' => 'gadsdentoday.com',
  'Gatestone Institute' => 'www.gatestoneinstitute.org',
  'Geller Report' => 'pamelageller.com',
  'Gen Z Conservative' => 'genzconservative.com',
  'Geology In' => 'www.geologyin.com',
  'Ghost.Report',
  'Girls Just Wanna Have guns' => 'girlsjustwannahaveguns.com',
  'Globe Magazine' => 'www.globemagazine.com',
  'Gnews' => 'gnews.org',
  'GOD Good Lord Above' => 'thegoodlordabove.com',
  'Godfather Politics' => 'godfatherpolitics.com',
  'Gold Country Today' => 'goldcountrytoday.com',
  'Golden State Today' => 'goldenstatetoday.com',
  'GoodGopher' => 'www.goodgopher.com',
  'Gop.gov House Republicans' => 'gop.gov',
  'Grain of Truth' => 'grainoftruth.ca',
  'Grand Canyon Times' => 'grandcanyontimes.com',
  'Great American Daily' => 'greatamericandaily.com',
  'Great American Republic' => 'https://greatamericanrepublic.com',
  'Grunge' => 'Grunge.com',
  'Gucmakale' => 'Gucmakale.com',
  'Gulf News' => 'gulfnews.com',
  'Hang The Bankers' => 'www.hangthebankers.com',
  'Hannity' => 'Hannity.com',
  'Hawar News Agancy' => 'en.hawarnews.com',
  'Head Topics' => 'headtopics.com',
  'Here is the Evidence' => 'hereistheevidence.com',
  'Heartland Institute' => 'www.heartland.org',
  'Hogg Watch' => 'www.hoggwatch.com',
  'Hoodsite' => 'Hoodsite',
  'Hot Springs Times' => 'hotspringstimes.com',
  'Huntsville Leader' => 'huntsvilleleader.com',
  'iHarare' => 'iharare.com',
  'I Hate the Media' => 'www.ihatethemedia.com',
  'I love my Freedom' => 'ilovemyfreedom.org',
  'I, Hypocrite' => 'ihypocrite.net',
  'Illegal Alien Crime Report' => 'www.illegalaliencrimereport.com',
  'Illicit Info' => 'illicitinfo.com',
  'IMOwired' => 'imowired.com',
  'Imperial CA News' => 'imperialcanews.com',
  'InfoGalactic' => 'infogalactic.com',
  'Independent Sentinel' => 'www.independentsentinel.com',
  'Information Liberation' => 'www.informationliberation.com',
  'InfoRos.ru',
  'InfoScum' => 'www.infoscum.com',
  'Inner Strength Zone' => 'innerstrength.zone',
  'Institute for Historical Review' => 'IHRihr.org',
  'Interior Alaska News' => 'interioralaskanews.com',
  'International Organization for the Family' => 'IOFprofam.org',
  'Jefferson Reporter' => 'jeffersonreporter.com',
  'Joe for America' => 'joeforamerica.com',
  'Jonesboro Times' => 'jonesborotimes.com',
  'Judicial Watch' => 'www.judicialwatch.org',
  'Just the Facts' => 'www.justthefacts.org',
  'Kern County Times' => 'kerncountytimes.com',
  'Kings County Times' => 'kingscountytimes.com',
  'Knights Templar International' => 'knightstemplarinternational.com',
  'Korean Central News Agency',
  'LADbible',
  'LA Harbor News' => 'laharbornews.com',
  'Lake Tahoe Sun' => 'laketahoesun.com',
  'Lancaster Courier' => 'lancastercourier.com',
  'Last Frontier News' => 'lastfrontiernews.com',
  'LAX Leader' => 'laxleader.com',
  'Left Action' => 'leftaction.com',
  'Left Exposed' => 'leftexposed.org',
  'Lew Rockwell' => 'www.lewrockwell.com',
  'Liberty Hangout' => 'libertyhangout.org',
  'Liberty Talk.fm' => 'libertytalk.fm',
  'Liberty Unyeilding',
  'Life News' => 'www.lifenews.com',
  'Live Leak' => 'www.liveleak.com',
  'London Web News' => 'londonwebnews.com',
  'Louder with Crowder' => 'louderwithcrowder.com',
  'Lowe Delta News' => 'lowedeltanews.com',
  'Lucianne.com' => 'https://www.lucianne.com',
  'Mad World News' => 'madworldnews.com',
  'MAGA Daily Report' => 'magadailyreport.com',
  'MagaPill' => 'www.magapill.com',
  'Marin Leader' => 'marinleader.com',
  'Mat-Su' => 'matsutimes.com',
  'Mehr News Agency' => 'en.mehrnews.com',
  'Merced Times' => 'mercedtimes.com',
  'Mercopress' => 'en.mercopress.com',
  'Metapedia' => 'en.metapedia.org',
  'Metric Media' => 'metricmedianews.com',
  'Middle American Democrat' => 'https://middleamericandemocrat.com',
  'Middle East Forum' => 'www.meforum.org',
  'Middle East Media Research Institute' => 'Memriwww.memri.org',
  'Mixi.Media' => 'mixi.media',
  'Mobile Courant' => 'mobilecourant.com',
  'Mohave Today' => 'mohavetoday.com',
  'Mondoweiss' => 'mondoweiss.net',
  'Monterey Times' => 'montereytimes.com',
  'MoonBattery' => 'moonbattery.com',
  'MoveOn' => 'front.moveon.org',
  'MSMLies.com',
  'My Right American' => 'myrightamerica.com',
  'National Alliance' => 'natall.com',
  'National Enquirer' => 'www.nationalenquirer.com',
  'National Policy Institute',
  'National Rifle Association' => 'home.nra.org',
  'National Right to Life Committee' => 'nrlc.org',
  'National Vanguard' => 'nationalvanguard.org',
  'Natural State News' => 'naturalstatenews.com',
  'NE Alabama News' => 'nealabamanews.com',
  'NE Cali News' => 'necalinews.com',
  'NE Sacramento News' => 'nesacramentonews.com',
  'NE Valley Times' => 'nevalleytimes.com',
  'New Nation News' => 'www.newnation.org',
  'News Blaze' => 'newsblaze.com',
  'News Break' => 'newsbreak.com',
  'News Heist' => 'newsheist.com',
  'News Punch' => 'newspunch.com',
  'News Rescue' => 'newsrescue.com',
  'Newsservis.com',
  'News with Views' => 'www.newswithviews.com',
  'NewsAmmo' => 'newsammo.com',
  'Newsmax' => 'www.newsmax.com',
  'Newsner' => 'en.newsner.com',
  'NewsWars' => 'newswars.com',
  'Next News Network',
  'NOQ Report' => 'noqreport.com',
  'Nordic Monitor' => 'nordicmonitor.com',
  'North Alaska News' => 'northalaskanews.com',
  'North Birmingham Times' => 'northbirminghamtimes.com',
  'North Central Arkansas News' => 'ncarkansasnews.com',
  'North Coast California News' => 'northcoastcanews.com',
  'North Inland News' => 'northinlandnews.com',
  'North Little Rock Times' => 'northlittlerocktimes.com',
  'North OC Times' => 'northoctimes.com',
  'North Pima News' => 'northpimanews.com',
  'North Sacramento Today' => 'northsactoday.com',
  'North SFV Today' => 'northsfvtoday.com',
  'North SGV News' => 'northsgvnews.com',
  'Not Allowed To' => 'notallowedto.com',
  'Now8News' => 'now8news.com',
  'NowThisNews' => 'nowthisnews.com',
  'NPR.News',
  'NRL News Today' => 'nationalrighttolifenews.org',
  'NTD.TV' => 'New Tang Dynastywww.ntd.tv',
  'NW Alabama News' => 'nwalabamanews.com',
  'NW Arkansas News' => 'nwarkansasnews.com',
  'NW LA Times' => 'nwlatimes.com',
  'NW Riverside News' => 'nwriversidenews.com',
  'NW Valley Times' => 'nwvalleytimes.com',
  'Oakland City Wire' => 'oaklandcitywire.com',
  'Oath Keepers' => 'www.oathkeepers.org',
  'Objectivist' => 'objectivist.co',
  'Occupy Democrats' => 'occupydemocrats.com',
  'Outraged Patriot' => 'outragedpatriot.com',
  'Overpasses for America' => 'overpassesforamerica.com',
  'Pacific Pundit' => 'www.pacificpundit.com',
  'Parler' => 'parler.com',
  'Patribotics Blog' => 'patribotics.blog',
  'Patriot Crier',
  'Patriot Journal' => 'patriotjournal.org',
  'Patriot Report' => 'patriotreport.com',
  'Patriotic Viral News' => 'patrioticviralnews.com',
  'PC Must Die News' => 'pcmustdie.com',
  'PeaceData' => 'peacedata.net',
  'Perez Hilton' => 'perezhilton.com',
  'Personal Liberty',
  'PHX Reporter' => 'phxreporter.com',
  'Pinal Today' => 'pinaltoday.com',
  'PJ Media' => 'pjmedia.com',
  'PM Nightly News' => 'pmnightlynews.com',
  'Polipace',
  'Political Flare' => 'politicalflare.com',
  'Political Insider' => 'www.thepoliticalinsider.com',
  'Political Mayhem News' => 'politicalmayhem.news',
  'Political State' => 'https://politicalstate.org/',
  'Politifact News' => 'www.politifact.news',
  'Pomona Valley News' => 'pomonavalleynews.com',
  'Population Research Institute' => 'pop.org',
  'Populist.Press',
  'Powdered Wig Society' => 'powderedwigsociety.com',
  'PragerU' => 'www.prageru.com',
  'Pravda Report' => 'pravdareport.com',
  'Press Corp' => 'presscorp.org',
  'Press TV' => 'www.presstv.com',
  'Prntly' => 'prntly.com',
  'Project Veritas' => 'projectveritas.com',
  'Proto Thema' => 'en.protothema.gr',
  'Pro Trump News' => 'protrumpnews.com/',
  'Pulaski Times' => 'pulaskitimes.com',
  'Puppet String News' => 'www.puppetstringnews.com',
  'Quillette' => 'quillette.com',
  'Raw Conservative Opinions' => 'rawconservativeopinions.com',
  'Real Conservatives Unite' => 'realconservativesunite.com',
  'Red Blue Divide' => 'redbluedivide.com',
  'Redding Today' => 'reddingtoday.com',
  'Red Ice TV' => 'redice.tv',
  'Red Orbit' => 'www.redorbit.com',
  'Red State Watcher' => 'redstatewatcher.com',
  'RedState',
  'Redwood Empire News' => 'redwoodempirenews.com',
  'Reed Cooper News' => 'https://www.reedcooper.net',
  'Renew America' => 'www.renewamerica.com',
  'Republican National Committee' => 'RNCgop.com',
  'Revolver.News',
  'Righter Way' => 'righterway.com',
  'Right Side News' => 'rightwingnews.com',
  'Right Wing Tribune',
  'River Region Times' => 'riverregiontimes.com',
  'Rodong Sinmun' => 'North Korea',
  'RT News' => 'www.rt.com',
  'Rudaw' => 'rudaw.net',
  'Ruptly' => 'ruptly.tv',
  'RushLimbaugh.com',
  'Russia Insider' => 'russia-insider.com',
  'Russia News Agency-TASS' => 'tass.com',
  'Ruth Institute' => 'www.ruthinstitute.org',
  'Sacramento Standard' => 'sacramentostandard.com',
  'Santa Monica Observer' => 'www.smobserved.com',
  'SC Alaska News' => 'scalaskanews.com',
  'SE Alaska News' => 'sealaskanews.com',
  'SE Arizona News' => 'searizonanews.com',
  'Secure America Now' => 'www.secureamericanow.org',
  'Shafaq News' => 'shafaaq.com',
  'Shoals Today' => 'shoalstoday.com',
  'SHTFplan.com' => 'www.shtfplan.com',
  'Sick Chirpse' => 'www.sickchirpse.com',
  'SkepticInk' => 'www.skepticink.com',
  'Sohu.com',
  'South Africa Today' => 'southafricatoday.net',
  'Sons of 1776' => 'sonsof1776.com',
  'South Alabama Times' => 'southalabamatimes.com',
  'Sputnik' => 'sputniknews.com',
  'Stares at the World' => 'www.staresattheworld.com',
  'State of the Nation' => 'stateofthenation.co',
  'Steadfast and Loyal' => 'steadfastandloyal.com',
  'Stone Cold Truth' => 'stonecoldtruth.com',
  'South Birmingham Times' => 'southbirminghamtimes.com',
  'South Pima News' => 'southpimanews.com',
  'Stranger than Fiction News' => 'stfnreport.com',
  'Strategic Culture Foundation' => 'www.strategic-culture.org',
  'Summit News',
  'SurvivalBlog.com' => 'https://survivalblog.com/',
  'SwampDrain.com' => 'swampdrain.com',
  'Swarajya' => 'swarajyamag.com',
  'SW Alaska News' => 'swalaskanews.com',
  'SW Arizona News' => 'swarizonanews.com',
  'SW Arkansas Times' => 'swarkansastimes.com',
  'SW Valley Times' => 'swvalleytimes.com',
  'Syria News',
  'Taki’s Magazine' => 'takimag.com',
  'Tasnim News Agency' => 'www.tasnimnews.com',
  'TB Daily News' => 'tbdailynews.com',
  'Tea Party Inc.' => 'www.teaparty.org',
  'Tea Party Patriots' => 'www.teapartypatriots.org',
  'TechStartups' => 'techstartups.com',
  'Teddy Stick' => 'teddystick.com',
  'Telesur' => 'www.telesurtv.net',
  'The African Exponent',
  'The American Mirror' => 'theamericanmirror.com',
  'The Angry Patriot' => 'www.angrypatriotmovement.com',
  'The Bearded Patriot' => 'thebeardedpatriot.com',
  'The Beltway Report' => 'thebeltwayreport.com/',
  'The Blacksphere' => 'theblacksphere.net',
  'The Blaze' => 'www.theblaze.com',
  'The Boston Tribune',
  'The Buffalo Chronicle',
  'The Conservative Brief' => 'www.theconservativebrief.com',
  'The Conservative Central' => 'theconservativecentral.com',
  'The Conservative Papers' => 'conservativepapers.com',
  'The Constitution',
  'The Daily Bell' => 'www.thedailybell.com',
  'The Daily Wire' => 'www.dailywire.com',
  'The DC Clothesline' => 'www.dcclothesline.com',
  'TheDonald.Win',
  'The Duran' => 'theduran.com',
  'The Economic Times' => 'economictimes.indiatimes.com',
  'The Epoch Times' => 'www.theepochtimes.com',
  'The Federalist' => 'thefederalist.com',
  'The Federalist Papers Project' => 'thefederalistpapers.org',
  'The Federation for American Immigration Reform' => 'www.fairus.org',
  'The Freedom Times' => 'thefreedomtimes.com',
  'The Free Patriot' => 'thefreepatriot.org',
  'The Free Telegraph' => 'freetelegraph.com',
  'The Frisky' => 'www.thefrisky.com',
  'The Gateway Pundit' => 'www.thegatewaypundit.com',
  'The Horn' => 'thehornnews.com',
  'The LA Post' => 'thelapost.com',
  'The Last Refuge' => 'theconservativetreehouse.com',
  'The Last Resistance' => 'lastresistance.com',
  'The Laugh Club' => 'thelaughclub.net',
  'The Liberty Daily' => 'thelibertydaily.com',
  'The Liberty Eagle' => 'www.thelibertyeagle.com',
  'The Majalla' => 'eng.majalla.com',
  'The Millennium Report' => 'themillenniumreport.com',
  'The National Patriot' => 'www.thenationalpatriot.com',
  'The National Pulse' => 'thenationalpulse.com',
  'The National' => 'UAEwww.thenational.ae',
  'The Nationalist Review' => 'nationalistreview.net',
  'The Other 98%' => 'other98.com',
  'ThePoliticalBrief.com',
  'The Politics Online',
  'The Post & Email' => 'www.thepostemail.com',
  'The Proud Liberal' => 'theproudliberal.org',
  'The Red Elephants',
  'The Religion of Peace' => 'www.thereligionofpeace.com',
  'The Remnant Newspaper' => 'remnantnewspaper.com',
  'The Right Scoop' => 'therightscoop.com',
  'The Right Stuff' => 'therightstuff.biz',
  'The Science News Reporter',
  'The Science Times' => 'sciencetimes.com',
  'The Sons of Liberty Media',
  'TheSpectator.info',
  'The Tehran Times' => 'www.tehrantimes.com',
  'The Times of America' => 'www.digifection.com',
  'The Union Journal' => 'theunionjournal.com',
  'The Unz Review' => 'www.unz.com',
  'The Washington Sentinel' => 'thewashingtonsentinel.com',
  'The Washington Standard',
  'Think Americana' => 'thinkamericana.com',
  'Today Breaking News' => 'chicagodaily.pro',
  'ToddStarnes.com',
  'TooFab' => 'toofab.com',
  'Top Topic' => 'www.toptopic.club',
  'Toronto Today' => 'torontotoday.net',
  'Townhall' => 'townhall.com',
  'TPL News' => 'tplnews.com',
  'Trending Politics' => 'trendingpolitics.com',
  'Trigger Reset' => 'triggerreset.net',
  'True Activist' => 'www.truthexam.com',
  'True Viral News' => 'trueviralnews.com',
  'Trump.News' => 'trump.news',
  'Trump Train News' => 'trumptrainnews.com',
  'Truth and Action' => 'www.truthandaction.org',
  'Truth in Media' => 'truthinmedia.com',
  'Truth Uncensored' => 'truthuncensored.net',
  'Tucson Standard' => 'tucsonstandard.com',
  'Turning Point USA' => 'www.tpusa.com',
  'Tuscaloosa Leader' => 'tuscaloosaleader.com',
  'Uncle Sam’s Misguided Children' => 'unclesamsmisguidedchildren.com',
  'Understanding the threat' => 'www.understandingthethreat.com',
  'Unite America First' => 'uniteamericafirst.com',
  'Upper Delta News' => 'upperdeltanews.com',
  'US Backlash' => 'usbacklash.org',
  'US Chronicle' => 'www.uschronicle.com',
  'UsLibertyWire.club',
  'US Liberty Wire' => 'https://uslibertywire.com/',
  'US National News' => 'usnationalnews.org',
  'USA is Online' => 'usaisonline.com',
  'USA Really' => 'usareally.com',
  'USA Supreme' => 'www.usasupreme.com',
  'USAnetwork.info' => 'usanetwork.info',
  'UsRight-Left.com',
  'USSA News' => 'ussanews.com',
  'Vanguard America' => 'bloodandsoil.org',
  'Vatican Radio' => 'en.radiovaticana.va',
  'Vdare' => 'www.vdare.com',
  'Verdugos News' => 'verdugosnews.com',
  'Vidmax' => 'vidmax.com',
  'Viral Cocaine' => 'viralcocaine.com',
  'Viral Hatch' => 'viralhatch.com',
  'Voice of Europe' => 'voiceofeurope.com',
  'WallBuilders' => 'wallbuilders.com',
  'Washington News Press' => 'fibrohealthnews.com',
  'Washington Pundit' => 'https://thewashingtonpundit.com',
  'Washington Times' => 'www.washingtontimes.com',
  'WayneDupree.com',
  'We The People Daily' => 'wethepeopledaily.com',
  'West Central Alabama News' => 'wcalabamanews.com',
  'Western Journal' => 'westernjournal.com',
  'What’s the Harm' => 'whatstheharm.net',
  'WikiIslam' => 'wikiislam.net',
  'Wings Over Scotland' => 'wingsoverscotland.com',
  'Wiregrass Times' => 'wiregrasstimes.com',
  'Witherspoon Institute' => 'www.thepublicdiscourse.com',
  'Woke Sloth' => 'wokesloth.com',
  'Women are Human' => 'womenarehuman.com',
  'Women’s Rights News' => 'facebook.com/WOMENSRIGHTSNEWS/',
  'World Net Daily' => 'www.wnd.com',
  'WorldStarHipHop' => 'worldstarhiphop.com',
  'Yavapai News' => 'yavapainews.com',
  'Yellowhammer Times' => 'yellowhammertimes.com',
  'Yes I’m Right' => 'yesimright.com',
  'YourContent' => 'yc.news',
  'Zenith News' => 'Zenith.news',
  'Zox' => 'Maga2020.usmaga2020.us)'
  );




















































































