9News – KUSA (9news.com)
12 News KPNX (12news.com)
24ur.com
38 North (www.38north.org)
680 News (www.680news.com)
1010 WINS AM (1010wins.radio.com)
1440 Newsletter (join1440.com)
ABC7Chicago.com
ABC7 New York (abc7ny.com)
ABC12/WJRT-TV (abc12.com)
ABS-CBN (news.abs-cbn.com)
ActionNewsJax.com
Ad Fontes Media (adfontesmedia.com/)
Adweek
Africa Check (africacheck.org)
AgDaily (agdaily.com)
Agence France-Presse (AFP) (www.afp.com)
Agenzia Nazionale Stampa Associata (ANSA) (http://www.ansa.it)
Agerpres (www.agerpres.ro)
AgWeb (agweb.com)
Air Force Times
Airwars (airwars.org)
Alabama Political Reporter (www.alreporter.com)
Alabama Today (altoday.com)
Albany Democrat-Herald (democratherald.com)
Algemeen Dagblad (ad.nl)
AllAfrica
Alliance For Securing Democracy (securingdemocracy.gmfus.org)
Amarillo Globe-News (www.amarillo.com)
American Heritage (www.americanheritage.com)
American Military News (americanmilitarynews.com)
American Press Institute (API) (www.americanpressinstitute.org)
AmoMama (news.amomama.com)
Anderson Independent Mail (independentmail.com)
APTN National News
Arc Digital (arcdigital.media)
Arizona Capitol Times (azcapitoltimes.com)
Army Times
Ars Technica (arstechnica.com)
Asheboro Courier-Tribune (courier-tribune.com)
Asia Times (www.atimes.com)
Associated Press (apnews.com)
Atlas Obscura (atlasobscura.com)
azfamily.com
Ballotpedia (ballotpedia.org)
Bangkok Post (www.bangkokpost.com)
Baxter Bulletin (www.baxterbulletin.com)
Belfer Center for Science and International Affairs (www.belfercenter.org)
Belleville News-Democrat (www.bnd.com)
Better Government Association (www.bettergov.org)
Big News Network (www.bignewsnetwork.com)
Big Think (bigthink.com)
Biloxi Sun Herald
Bismarck Tribune (bismarcktribune.com)
BlastingNews (us.blastingnews.com)
Bleeping Computer (https://www.bleepingcomputer.com)
BNO News (bnonews.com)
Bozeman Daily Chronicle
Bridge Magazine (www.bridgemi.com)
Bring Me The News (bringmethenews.com)
Bullshido (www.bullshido.net)
Burnett County Sentinel
Business2Community (www.business2community.com)
C-Span (www.c-span.org)
Canadian Public Affairs Channel (CPAC) (www.cpac.ca)
Cape Cod Times (www.capecodtimes.com)
Capitol Fax (capitolfax.com)
Casper Star-Tribune (trib.com)
Castanet (www.castanet.net)
CBS Philly (philadelphia.cbslocal.com)
Center for Democracy and Technology (cdt.org)
Center for Responsive Politics (www.opensecrets.org)
Center for strategic and International studies (www.csis.org)
Channel News Asia – CNA (channelnewsasia.com)
Charity Navigator (charitynavigator.org)
Chattanooga Times Free Press (timesfreepress.com)
Chinook Observer (www.chinookobserver.com)
Christian Science Monitor (www.csmonitor.com)
Cinncinati Equirer (www.cincinnati.com)
CNET (www.cnet.com)
Committee for Economic development (www.ced.org)
Committee to Protect Journalists (www.cpj.org)
Concord Monitor (www.concordmonitor.com)
Congress.gov (www.congress.gov)
Congressional Budget Office (CBO) (www.cbo.gov)
Constitution Daily (constitutioncenter.org)
Consumer Reports (www.consumerreports.org)
Consumerist (consumerist.com)
Cook Political Reports (cookpolitical.com)
Coriere della Sera (corriere.it)
Coronavirus.gov
Council on Foreign Relations (www.cfr.org)
Countable News (www.countable.us)
Courthouse News Service (www.courthousenews.com)
Covid Tracking Project (covidtracking.com)
CP24 (www.cp24.com)
Crimeola (crimeola.com)
CTV News (www.ctvnews.ca)
D.C. Circuit Breaker (dccircuitbreaker.org)
Daily Business Review (www.dailybusinessreview.com)
Daily Camera (dailycamera.com)
Daily Journal (Illinois)
Daily Journal (Missouri) (dailyjournalonline.com)
Daily Maverick (dailymaverick.co.za)
Daily Record (www.dailyrecord.com)
Darien Times (www.darientimes.com)
Dayton Daily News (www.daytondailynews.com)
Defense News (www.defensenews.com)
Defense One (www.defenseone.com)
Del Rio News-Herald (delrionewsherald.com)
Denton Record-Chronicle
Des Moines Register (www.desmoinesregister.com)
Detik.com
DifferenceBetween.net (www.differencebetween.net)
Digital Journal (www.digitaljournal.com)
Doctors Without Borders (www.doctorswithoutborders.org)
DPA German Press Agency (www.dpa-international.com)
Duluth News Tribune (www.duluthnewstribune.com)
Eagle Tribune
East Idaho News (eastidahonews.com)
Eau Claire Leader-Telegram (leadertelegram.com)
EJ Insight (www.ejinsight.com)
Elko Daily Free Press
El Nuevo Dia (elnuevodia.com)
Erie Times-News (www.goerie.com)
ERR News (Estonia Public Broadcasting) (news.err.ee)
Eurasia Group (www.eurasiagroup.net)
Every CRS Report (www.everycrsreport.com)
Fact Check (www.factcheck.org)
Factwire News Agency (www.factwire.org)
Fair Observer (www.fairobserver.com)
Fayetteville Observer (fayobserver.com)
Federal News Network (federalnewsnetwork.com)
Federal Times (www.federaltimes.com)
Financial Times (www.ft.com)
First Coast News (firstcoastnews.com)
First Draft News (firstdraftnews.org)
Florida Politics (floridapolitics.com)
Florida Times Union (jacksonville.com)
Foreign Affairs (www.foreignaffairs.com)
Foreign Policy (foreignpolicy.com)
Foster’s Daily Democrat (fosters.com)
France 24 (www.france24.com)
Full Fact UK (fullfact.org)
Gainesville Sun (gainesville.com)
Gallup (www.gallup.com)
Geek.com (geek.com)
Global Integrity (www.globalintegrity.org)
Global Slavery Index (www.globalslaveryindex.org)
Globe Gazette (Iowa) (globegazette.com)
GoodNewsNetwork (www.goodnewsnetwork.org)
Government Accountability Office (GAO) (www.gao.gov)
GovTrack (www.govtrack.us)
Great Falls Tribune (www.greatfallstribune.com)
Green Bay Press-Gazette (www.greenbaypressgazette.com)
Greenville News (www.greenvilleonline.com)
Group of Thirty (group30.org)
Hanford Sentinel (https://hanfordsentinel.com)
Harvard Business Review (hbr.org)
Harvard Gazette (news.harvard.edu)
Hastings Tribune
Healthcare Finance News (www.healthcarefinancenews.com)
Herald & Review (herald-review.com)
Hoax Slayer (www.hoax-slayer.com)
Homeland Security News Wire (www.homelandsecuritynewswire.com)
How Stuff Works (www.howstuffworks.com)
How-To Geek
I24 News (www.i24news.tv)
Icitizen (icitizen.com)
Idaho Statesman (www.idahostatesman.com)
iMediaEthics (www.imediaethics.org)
Inc. Magazine (inc.com)
Independent Journal Review (ijr.org)
Independent Record (Montana) (helenair.com)
Independent Voter Network (IVN) (ivn.us)
IndexMundi (indexmundi.com)
Indianapolis Star (www.indystar.com)
Inland Valley Bulletin (www.dailybulletin.com)
Institute for Women’s Policy Research (IWPR) (iwpr.org)
International Consortium of Investigative Journalists (www.icij.org)
International Energy Agency (www.iea.org)
International Organization (journals.cambridge.org)
International Press Institute (www.freemedia.at)
International Rescue Committee (www.rescue.org)
Investigative Reporters and Editors (www.ire.org)
Investopedia (www.investopedia.com)
Jackson Sun (www.jacksonsun.com)
Janes 360 (www.janes.com)
Japan Times (www.japantimes.co.jp)
Jewish Telegraphic Agency (JTA) (www.jta.org)
Journal Gazette (journalgazette.net/)
Justice Denied (justicedenied.org)
Kaiser Family Foundation (kff.org)
KAIT8-TV (kait8.com)
KBMT – 12NewsNow.com
KCRA 3 (kcra.com)
KDKA – CBS Pittsburgh (pittsburgh.cbslocal.com)
KDVR-TV (kdvr.com)
KERO TV – 23ABC (turnto23.com)
KETV (ketv.com)
KIRO 7 (kiro7.com)
KITV (kitv.com)
KMOV (www.kmov.com)
Know Your Meme (knowyourmeme.com)
Knowhere (knowherenews.com)
Knoxville News Senitinel (www.knoxnews.com)
KOAM News Now (koamnewsnow.com)
Kompas.com
KSTP-TV (kstp.com)
KTLA (ktla.com)
KTUU-TV (ktuu.com)
KTVA 11 (ktva.com)
KTVU Fox 2 (ktvu.com)
KWTV-News9 (news9.com)
La Devoir (ledevoir.com)
La Libre (lalibre.be)
Lansing State Journal (lansingstatejournal.com)
Las Cruces Sun-News (https://www.lcsun-news.com)
Law.com (law.com)
Law360 (law360.com)
Lawfare Blog (lawfareblog.com)
Lead Stories (leadstories.com)
Lebanon Daily News (ldnews.com)
Le Soir (lesoir.be)
Lima Charlie News (limacharlienews.com)
Lincoln Journal Star (journalstar.com)
LNP – LancasterOnline (lancasteronline.com)
Lompoc Record (lompocrecord.com)
Longview News-Journal
Loveland Reporter-Herald (reporterherald.com)
MakeUseOf (www.makeuseof.com)
Memeorandum (www.memeorandum.com)
Memphis Commercial Appeal (commercialappeal.com)
Mental Floss (mentalfloss.com)
Merion West (merionwest.com)
MetroWest Daily News (www.metrowestdailynews.com)
NewsNation (newsnationnow.com)
Military.com (www.military.com)
Military Times (www.militarytimes.com)
Missoulian (missoulian.com)
MLive (Michigan – Booth Newpapers)
Montana Standard (mtstandard.com)
Morning Consult (morningconsult.com)
Napa Valley Register (napavalleyregister.com)
National Bureau of Economic Research (www.nber.org)
National Conference of State Legislatures (NCSL) (http://www.ncsl.org)
National Institute on Money in State Politics (www.followthemoney.org)
National Journal (www.nationaljournal.com)
NationMaster (www.nationmaster.com)
Navy Times (navytimes.com)
Need2Know (theneed2know.com)
New Bern Sun Journal (www.newbernsj.com)
New Zealand Herald (www.nzherald.co.nz)
News and News (newsandnews.com)
News Channel 4 (KFOR.com) (kfor.com)
News Facts Network (NFN) (newsfactsnetwork.com)
News Lookup (www.newslookup.com)
News24 (South Africa) (www.news24.com)
Newsela (newsela.com)
Newsguard (www.newsguardtech.com)
NewsNet (YourNewsNet.com) (http://yournewsnet.com)
NewsNow UK (www.newsnow.co.uk)
News Straits Times (nst.com.my)
NewzJunky.com
NextGOV (www.nextgov.com)
Niskanen Center (niskanencenter.org)
NK News (www.nknews.org)
No Labels (www.nolabels.org)
Noozhawk (www.noozhawk.com)
Norfolk Daily News
North Korea Times (www.northkoreatimes.com)
Northwest Florida Daily News (nwfdailynews.com)
Northwest Indiana Times (www.nwitimes.com)
Novinite (www.novinite.com)
Oil Price (oilprice.com)
Oyez Project (www.oyez.org)
Pacific Daily News (www.guampdn.com)
Patch (patch.com)
Patheos (www.patheos.com)
Pensacola News Journal (www.pnj.com)
Peoria Journal Star (pjstar.com)
Peterson Foundation (www.pgpf.org)
Peterson Institute for International Economics (piie.com)
Pew Research (www.pewresearch.org)
Places Journal (placesjournal.org)
Pocono Record (www.poconorecord.com)
Political Wire (politicalwire.com)
Polygraph.info (www.polygraph.info)
Poynter Institute (www.poynter.org)
PR Newswire (prnewswire.mediaroom.com)
Procon.org (www.procon.org)
Public Policy Polling (www.publicpolicypolling.com)
Public Religion Research Institute (www.prri.org)
Quad City Times (qctimes.com)
Radio Free Europe / Radio Liberty (www.rferl.org)
Rand Corporation (www.rand.org)
Rapid City Journal (rapidcityjournal.com)
Rare News (rare.us)
Recode (www.recode.net)
Relevant Magazine (relevantmagazine.com)
Reporter Without Borders (rsf.org)
Reporters Lab (reporterslab.org)
Reuters (www.reuters.com)
RFI – Radio France Internationale (rfi.fr/en/)
RiverBender.com
Riverdale Press (riverdalepress.com)
Roll Call (www.rollcall.com)
RTE (Radio Television of Ireland) (www.rte.ie)
Russian Media Monitor (www.russialies.com)
San Diego Union Tribune (www.sandiegouniontribune.com)
San Marcos Daily Record (www.sanmarcosrecord.com)
Santa Maria Times (santamariatimes.com)
Sarasota Herald-Tribune (www.heraldtribune.com)
Sayfie Review (www.sayfiereview.com)
Science Debate (sciencedebate.org)
Scoopnest (www.scoopnest.com)
SCOTUSblog (www.scotusblog.com)
Shareably (www.shareably.net)
Shorenstein Center (shorensteincenter.org)
Shreveport Times (shreveporttimes.com)
Simple Politics (www.simplepolitics.co.uk)
Sioux City Journal (siouxcityjournal.com)
Sky News (news.sky.com)
SmartNews (www.smartnews.com)
Snopes (www.snopes.com)
South Bend Tribune
South Florida Sun-Sentinel (www.sun-sentinel.com)
Spectrum News – NY1 (www.ny1.com)
Spectrum Report (spectrumreport.com)
St. Cloud Times (www.sctimes.com)
Stars and Stripes (www.stripes.com)
Staten Island Advance (www.silive.com)
Statesman Journal (www.statesmanjournal.com)
Statesville Record & Landmark
Statista
Stimson Center (stimson.org)
StrategyPage (www.strategypage.com)
Stratfor (www.stratfor.com)
Taipei Times (www.taipeitimes.com)
Task and Purpose (taskandpurpose.com)
Telegram & Gazette
Texas Standard (www.texasstandard.org)
That’s Nonsense (www.thatsnonsense.com)
The Auburn Citizen (auburnpub.com)
The Australian Financial Review (www.afr.com)
The Balance (www.thebalance.com)
The Battlefords News Optimist
The Canadian Press (www.thecanadianpress.com)
The Cipher Brief (www.thecipherbrief.com)
The Columbian (columbian.com)
The Conversation (theconversation.com)
The Daily Chronicle (daily-chronicle.com)
The Daily Gazette (dailygazette.com)
The Daily News (Longview) (tdn.com)
The Daily Northwestern (dailynorthwestern.com)
The Daily Progress (www.dailyprogress.com)
The Day (New London) (www.theday.com)
The Defcon Warning System (www.defconwarningsystem.com)
The Diplomat Magazine (thediplomat.com)
The Economist (www.economist.com)
The Flip Side (theflipside.io)
The Herald Journal (Utah)
The Herald News (Massachusetts)
The Herald-Dispatch
The Herald-Sun (Durham, North Carolina) (www.heraldsun.com)
The Hill (thehill.com)
The Jamestown Foundation (jamestown.org)
The Jordan Times (www.jordantimes.com)
The Journal Standard (www.journalstandard.com)
The Macon Telegraph (www.macon.com)
The Marietta Times (mariettatimes.com)
The Marshall Project (www.themarshallproject.org)
The Meme Policeman (memepoliceman.com)
The Moderated Media (www.themoderatedmedia.com)
The Modesto Bee (www.modbee.com)
The Monitor (Texas)
The Morning Call (www.mcall.com)
The Nevada Independent (thenevadaindependent.com)
The News (Mexico City) (www.thenews.mx)
The News International (www.thenews.com.pk)
The News Literacy Project (www.thenewsliteracyproject.org)
The Outlook (Monmouth University) (outlook.monmouth.edu)
The Pantagraph (www.pantagraph.com)
The Post and Courier (www.postandcourier.com)
The Post Star (poststar.com)
The Post-Standard (Syracuse) (www.syracuse.com)
The Record – Stockton (recordnet.com)
The Register UK
The Republic (Indiana) (therepublic.com)
The Republican (Masslive) (www.masslive.com)
The Scotsman (www.scotsman.com)
The Sentinel (Pennsylvania) (cumberlink.com)
The Smoking Gun (www.thesmokinggun.com)
The Sociable (sociable.co)
The Southern Illinoisan (thesouthern.com)
The Star Democrat
The Strategy Bridge (thestrategybridge.org)
The Tennessean (tennessean.com)
The Times (Illinois) (www.mywebtimes.com)
The Times and Democrat (thetandd.com)
The Town Talk (thetowntalk.com)
The TruthSetter (truthsetter.com)
The Vindicator (vindy.com)
The Waterloo-Cedar Falls Courier (wcfcourier.com)
The ZDF (Zweites Deutsches Fernsehen) (www.zdf.de)
Third Way (www.thirdway.org)
ThoughtCo (www.thoughtco.com)
Times of San Diego (timesofsandiego.com)
Times-News (Idaho) (magicvalley.com)
Today I Found Out (www.todayifoundout.com)
Transparency International (www.transparency.org)
Transpartisan Review (transpartisanreview.com/)
Traverse City Record-Eagle
Tribune Content Agency (tribunecontentagency.com)
Tri-City Herald (tri-cityherald.com)
TruthorFiction.com (www.truthorfiction.com)
Tut.by
TVW Washington State (www.tvw.org)
Undark (undark.org)
United Press International (UPI) (www.upi.com)
United State House of Representatives (www.house.gov)
USA Spending (www.usaspending.gov)
USAFacts (www.usafacts.org)
Utah Standard-Examiner (www.standard.net)
Vera Files (verafiles.org)
Viral Thread (www.viralthread.com)
Voice of America (www.voanews.com)
Vos Iz Neias (www.vosizneias.com)
Vote Smart (votesmart.org)
Waco Tribune-Herald (https://www.wacotrib.com)
War on the Rocks (warontherocks.com)
Washington Journal (C-Span)
Washington’s Top News (WTOP) (wtop.com)
WBTV (wbtv.com)
WCAX3 (wcax.com)
WDIV – ClickOnDetroit (clickondetroit.com)
We are the Mighty (www.wearethemighty.com)
WETM – MyTwinTiers.com
WFMYnews2.com
WFMZ (wfmz.com)
WGHP – Fox8 (myfox8.com)
WGN News (wgntv.com)
WikiNews (en.wikinews.org)
Wikipedia (www.wikipedia.org)
WikiTribune (www.wikitribune.com)
Winnipeg Free Press (winnipegfreepress.com)
Winona Daily News
Winston-Salem Journal
WION (World is One News) (www.wionews.com)
Wisconsin State Journal (host.madison.com)
WMUR9 (wmur.com)
WOFL (fox35orlando.com)
World Economic Forum (www.weforum.org)
World News (wn.com)
Worldometer (worldometers.info)
World Politics Review (www.worldpoliticsreview.com)
World Population Review (worldpopulationreview.com)
WPXI (wpxi.com)
WRAL
WSAZ News Channel (wsaz.com)
WTAE Pittsburgh’s Action News (wtae.com)
WTVF – Newschannel5 (newschannel5.com)
WTXF-TV Fox 29 (fox29.com)
WUSA9.com
WVEC – 13newsnow.com
WXIA – 11alive.com
ZDNet (zdnet.com)
