ACHNews (achnews.org)
Act.TV (act.tv)
Aftonbladet
Al DIA
Alliance for Justice (AFJ) (www.afj.org)
Alt News
Alternet (www.alternet.org)
Amandla (aidc.org.za)
America Blog (americablog.com)
American Bridge 21st Century (americanbridgepac.org)
American News X (americannewsx.com)
American Oversight
Americans United for Separation of Church and State (www.au.org)
Angry White Men (angrywhitemen.org)
Anti-Fascist News (antifascistnews.net)
AutoStraddle (www.autostraddle.com)
Baltimore City Paper (www.citypaper.com)
Bay Area Reporter (www.ebar.com)
Being Liberal (www.themaven.net)
BillMoyers.com (billmoyers.com)
Bitch Media (bitchmedia.org)
Black Agenda Report (blackagendareport.com)
Black America Web (blackamericaweb.com)
Black Lives Matter (blacklivesmatter.com)
Black Main Street (blackmainstreet.net)
Blue State Daily (bluestatedaily.com)
BoingBoing (boingboing.net)
Boston Review (bostonreview.net)
Bust Magazine (bust.com)
Canada Fact Check (canadafactcheck.ca)
Canadian Dimension (canadiandimension.com)
Capital & Main (capitalandmain.com)
Care2 (www.care2.com)
Ceasefire Magazine (ceasefiremagazine.co.uk)
Center for American Progress (www.americanprogress.org)
Center for Media and Democracy (www.prwatch.org)
Center for a Stateless Society (c4ss.org)
Change.org (https://www.change.org/)
Chicago Reader (www.chicagoreader.com)
Chicago Reporter (chicagoreporter.com)
China Internet Information Center (china.org.cn)
Citizen Critics (citizencritics.org)
CNN (www.cnn.com)
Code Pink (www.codepink.org)
Columbus Free Press (https://columbusfreepress.com/)
Comic Sands
Common Dreams (www.commondreams.org)
Cop Block (copblock.org)
Cosmopolitan (www.cosmopolitan.com)
CounterCurrents.org (www.countercurrents.org)
CounterPunch (www.counterpunch.org)
Crikey (crikey.com.au)
CrimethInc (crimethinc.com)
Crooked Media (crooked.com)
Crooks and Liars (crooksandliars.com)
Current Affairs (www.currentaffairs.org)
Curve Magazine (www.curvemag.com)
Daily Beast (www.thedailybeast.com)
Daily Dot (www.dailydot.com)
Daily Kos
Daily News bin
Daily Record (Scotland) (www.dailyrecord.co.uk)
Daily Sound and Fury (dailysoundandfury.com)
Dallas Voice (www.dallasvoice.com)
DeadState (deadstate.org)
Deadspin (deadspin.com)
Deep South Voice (deepsouthvoice.com)
Democracy Chronicles (democracychronicles.org)
Democracy Guardian
Democracy Journal (democracyjournal.org)
Democracy Now (www.democracynow.org)
Democratic Underground (www.democraticunderground.com)
Deshabhimani (https://www.deshabhimani.com/)
DeSmog (www.desmogblog.com)
Detroit Metro News
Dissent Magazine (www.dissentmagazine.org)
Drudge Retort (www.drudge.com)
Earth First Journal (earthfirstjournal.org)
Ecowatch (www.ecowatch.com)
Egberto Willies (egbertowillies.com)
Electoral-Vote.com (www.electoral-vote.com)
Electronic Intifada (electronicintifada.net)
Elite Daily (elitedaily.com)
Elle Magazine (elle.com)
Esquire Magazine (www.esquire.com)
Everyday Feminism (everydayfeminism.com)
Evonomics (evonomics.com)
ExtraNewsFeed
Feminist Current (www.feministcurrent.com)
Feministing (feministing.com)
Fifth Column News (thefifthcolumnnews.com)
Fifth Estate (www.fifthestate.org)
Finnish News (finnishnews.fi)
Food and Water Watch (www.foodandwaterwatch.org)
Foreign Policy Journal (www.foreignpolicyjournal.com)
Foreign Policy News (foreignpolicynews.org)
Free Press (freepress.org)
Free Rein News (frnewsreport.com)
Freedom From Religion Foundation (ffrf.org)
Freedom News and Journal (freedomnews.org.uk)
Front Page Live (www.frontpagelive.com)
FSTv (Freespeech.org) (www.freespeech.org)
Geopolitics Alert (geopoliticsalert.com)
Gizmodo (gizmodo.com)
Global Voices (globalvoices.org)
Good Magazine (www.good.is)
GQ Magazine (www.gq.com)
Grasping Reality With Both Hands: Bradford Delong (www.bradford-delong.com)
Green Left Weekly (www.greenleft.org.au)
Grit Post (gritpost.com)
Guardian Liberty Voice (guardianlv.com)
Guardians of Democracy (theguardiansofdemocracy.com)
Haaretz (www.haaretz.com)
Hill Reporter (hillreporter.com)
Huffington Post (www.huffingtonpost.com)
Human Rights Campaign (www.hrc.org)
In Defence of Marxism (www.marxist.com)
In These Times (inthesetimes.com)
Inequality Media (www.inequalitymedia.org)
Informed Comment (Juan Cole) (www.juancole.com)
Institute for Policy Studies (www.ips-dc.org)
International Viewpoint (www.internationalviewpoint.org)
Intrepid Report (www.intrepidreport.com)
Iowa Starting Line (iowastartingline.com)
It’s Going Down (itsgoingdown.org)
Jacobin (www.jacobinmag.com)
Jezebel (jezebel.com)
JoeBiden.com
Latest.com (latest.com)
Lavender Magazine (www.lavendermagazine.com)
LA Weekly (laweekly.com)
Left Foot Forward (leftfootforward.org)
Left Over Rights (leftoverrights.com)
Left Voice (www.leftvoice.org)
LeftScoop (www.leftscoop.com)
LGBTQ Nation (www.lgbtqnation.com)
Libcom.org (libcom.org)
Liberal America (liberalamerica.life)
Liberal Examiner (www.liberalexaminer.com)
Liberation News (www.liberationnews.org)
Little Green Footballs (littlegreenfootballs.com)
Mashable (mashable.com)
Media Matters (mediamatters.org)
Mediaite (www.mediaite.com)
Meduza (meduza.io)
MeidasTouch (meidastouch.com)
Merry Jane (www.merryjane.com)
Miami New Times (www.miaminewtimes.com)
Middle East Monitor (www.middleeastmonitor.com)
Modern Liberals (modernliberals.com)
Molad The Center for the Renewal of Israeli Democracy (www.molad.org)
Monthly Review (monthlyreview.org)
Moon of Alabama (www.moonofalabama.org)
Ms. (Magazine) (www.msmagazine.com)
MSNBC (www.msnbc.com)
Nation of Change (www.nationofchange.org)
National Association for the Advancement of Colored People (NAACP) (www.naacp.org)
Natural Resources Defense Council (www.nrdc.org)
NC Policy Watch (www.ncpolicywatch.com)
New Internationalist (newint.org)
New Politics Magazine (newpol.org)
New Republic (newrepublic.com)
New Statesman (www.newstatesman.com)
New York Amsterdam News (amsterdamnews.com)
New York Magazine (nymag.com)
New Yorker (www.newyorker.com)
News Corpse (newscorpse.com)
News Hounds (www.newshounds.us)
NewsOne (www.newsone.com)
North99 (north99.org)
Now Magazine (nowtoronto.com)
Occupy.com (www.occupy.com)
One Green Planet (www.onegreenplanet.org)
OpEdNews (OEN) (www.opednews.com)
Out Magazine (out.com)
Palmer Report (www.palmerreport.com)
Paste Magazine (www.pastemagazine.com)
Peacock Panache (www.peacock-panache.com)
People for the American Way (PFAW) (www.pfaw.org)
People Magazine (people.com)
PINAC (photographyisnotacrime.com)
Pink News (www.pinknews.co.uk)
Political Dig (politicaldig.com)
Political Tribune (politicaltribune.org)
PoliticusUsa (www.politicususa.com)
Politizoom (politizoom.com)
Popular Information (popular.info)
Popular Resistance (popularresistance.org)
Press Progress (www.pressprogress.ca)
Progressive Army (progressivearmy.com)
Progressive Change Campaign Committee (boldprogressives.org)
Project Censored (projectcensored.org)
Queerty (www.queerty.com)
Rabble.ca (rabble.ca)
Rantt Media (rantt.com)
Rappler (www.rappler.com)
Raw Story (www.rawstory.com)
Reader Supported News (RSN) (readersupportednews.org)
Reading the Pictures (www.readingthepictures.org)
Real News Network (therealnews.com)
Red Pepper (www.redpepper.org.uk)
Refinery29 (refinery29.com)
Republicans Suck (republicanssucks.org)
Republic Report (www.republicreport.org)
Resilience (Post Carbon Institute) (www.resilience.org)
Revcom.us (revcom.us)
ReWire.news (rewire.news)
Right Wing Watch (www.rightwingwatch.org)
Ring of Fire (trofire.com)
Rolling Stone (www.rollingstone.com)
Salon (www.salon.com)
San Francisco Bay View (sfbayview.com)
Scary Mommy (www.scarymommy.com)
Second Nexus (secondnexus.com)
Seventeen
Shadow Proof (shadowproof.com)
ShareBlue (shareblue.com)
Shondaland (shondaland.com)
Slate (www.slate.com)
Sludge (readsludge.com)
Smirking Chimp
Socialist Standard (www.worldsocialism.org)
SocialistWorker.org (socialistworker.org)
Source Politics (sourcepolitics.com/)
SourceWatch (www.sourcewatch.org)
Southern Poverty Law Center (www.splcenter.org)
Splinter (splinternews.com)
St. Pete for Peace (www.stpete4peace.org)
Syriana Analysis (www.syriana-analysis.com)
Talking Points Memo (talkingpointsmemo.com)
Teen Vogue (teenvogue.com)
The Advocate (www.advocate.com)
The American Independent Institute (americanindependent.com)
The American Prospect (prospect.org)
The Austin Chronicle (www.austinchronicle.com)
The Blue Route (www.blue-route.org)
The Burning Spear (www.theburningspear.com)
The Canary (UK) (www.thecanary.co)
The Climate Reality Project (www.climaterealityproject.org)
The Cut (thecut.com)
The Daily 49er (www.daily49er.com)
The Daily Banter (thedailybanter.com)
The Daily Buzz (the-daily.buzz)
The Daily Poster (dailyposter.com)
The Daily Vox (www.thedailyvox.co.za)
The Democratic Hub (www.democratichub.com)
The Dodo (https://www.thedodo.com)
The Dworkin Report (dworkinreport.com)
The Florida Squeeze (thefloridasqueeze.com)
The Ghion Journal (ghionjournal.com)
The Improper Magazine (www.theimproper.com)
The Indypendent (indypendent.org)
The Intellectualist (theintellectualist.co)
The Lily (www.thelily.com)
The London Economic (www.thelondoneconomic.com)
The Mary Sue (www.themarysue.com)
The Militant (www.themilitant.com)
The Monthly (Australia) (www.themonthly.com.au)
The Morning Star (www.morningstaronline.co.uk)
The Nation (https://www.thenation.com/)
The National Memo (www.nationalmemo.com)
The New Civil Rights Movement (www.thenewcivilrightsmovement.com)
The Outline (theoutline.com)
The Palestine Chronicle (www.palestinechronicle.com)
The Phnom Penh Post (www.phnompenhpost.com)
The Progressive (www.progressive.org)
The Progressive Frontier (progressivefrontier.com)
The Reality-Based Community (www.samefacts.com)
The Root (www.theroot.com)
The Source Newspaper (La Source) (thelasource.com)
The Stern Facts (thesternfacts.com)
The Stranger (www.thestranger.com)
The Texas Observer (www.texasobserver.org)
The Village Voice (www.villagevoice.com)
The Walrus (thewalrus.ca)
The Washington Spectator (washingtonspectator.org)
The Week (theweek.com)
The World Can’t Wait (worldcantwait.net)
TheGrio (thegrio.com)
The Zero Hour (www.thisisthezerohour.com)
Them.us
TheosWatch.com (theoswatch.com)
Think Progress (thinkprogress.org)
This Magazine (this.org)
Towleroad (www.towleroad.com)
TreeHugger (www.treehugger.com)
TruthDig (www.truthdig.com)
TruthOut (truthout.org)
Truth Theory (truththeory.com)
Unicorn Riot (www.unicornriot.ninja)
Uproxx (uproxx.com)
Upworthy (www.upworthy.com)
Vanity Fair (www.vanityfair.com)
Vermont Independent (www.vermontindependent.org)
Verrit (verrit.com)
Viral Title (viraltitle.com)
Vote
Vox (www.vox.com)
Wall Street on Parade (wallstreetonparade.com)
Washington Babylon (washingtonbabylon.com)
Washington Daily Wire
Washington Press (washingtonpress.com)
Washington Sources (washingtonsources.org)
Washingtonian (washingtonian.com)
Wear Your Voice (wearyourvoicemag.com)
We Hunted the Mammoth (wehuntedthemammoth.com)
White House Watch (whitehousewatch.com)
Who.What.Why (whowhatwhy.org)
Wonkette (wonkette.com)
Workers World (www.workers.org)
World Socialist Web Site (wsws.org)
Yes Magazine (www.yesmagazine.org)
Young Turks (tytnetwork.com)
Your Black World (yourblackworld.net)
Z Magazine (zcomm.org)
