604 Now (604now.com)
972 Magazine (972mag.com)
1600 Daily (www.whitehouse.gov)
ABC News (abcnews.go.com)
ABC News Australia (www.abc.net.au)
ABC11 Eyewitness News (abc11.com)
Above the Law (abovethelaw.com)
AceShowbiz (aceshowbiz.com)
ACLU (www.aclu.org)
Aeon (aeon.co)
Affinity Magazine (affinitymagazine.us)
African Arguments (africanarguments.org)
Africa News (www.africanews.com)
Ahval News (ahvalnews.com)
Akron Beacon Journal (beaconjournal.com)
Al Jazeera (www.aljazeera.com)
Al Monitor (www.al-monitor.com)
Al-Sura (al-sura.com)
Alan Guttmacher Institute (www.guttmacher.org)
Albany Times-Union (www.timesunion.com)
Alberta Views (https://albertaviews.ca)
AllGov (www.allgov.com)
Allied Progress (alliedprogress.org)
AM New York (www.amny.com)
America Magazine (www.americamagazine.org)
American Immigration Council (www.americanimmigrationcouncil.org)
American Public Media (mediabiasfactcheck.com)
Amnesty International (www.amnesty.org)
Anchorage Daily News (adn.com)
Anniston Star (www.annistonstar.com)
Anthropocene Magazine (www.anthropocenemagazine.org)
Anti Defamation League (www.adl.org)
AOL (www.aol.com)
APM Reports (www.apmreports.org)
Areo Magazine
Arizona Daily Star (tucson.com)
Arizona Daily Sun (azdailysun.com)
Arizona Republic (www.azcentral.com)
Arkansas Times (www.arktimes.com)
Arms Control Association (https://www.armscontrol.org)
ARTE (arte.tv)
Asheville Citizen-Times (www.citizen-times.com)
Asia Sentinel
Asian Correspondent (asiancorrespondent.com)
Atavist Magazine (magazine.atavist.com)
Atlanta Black Star (atlantablackstar.com)
Atlanta Journal-Constitution (www.ajc.com)
Atlantic (www.theatlantic.com)
Atlantic Media (www.atlanticmedia.com)
ATTN: (www.attn.com)
Austin American-Statesman (www.statesman.com)
Austin Daily Herald (austindailyherald.com)
AV Club (avclub.com)
Axios (www.axios.com)
BackChannel (backchannel.com)
Balkan Insight (balkaninsight.com)
Baltimore Sun (www.baltimoresun.com)
Bangor Daily News (bangordailynews.com)
Baptist News Global (baptistnews.com)
Battle Creek Enquirer (www.battlecreekenquirer.com)
BBC News (www.bbc.com)
Bellingcat (www.bellingcat.com)
Bellingham Herald (bellinghamherald.com)
Berkeleyside (www.berkeleyside.com)
Berkshire Eagle (www.berkshireeagle.com)
Berliner Zeitung (berliner-zeitung.de)
Bing News (www.bing.com)
Birmingham Mail (www.birminghammail.co.uk)
Bleacher Report (bleacherreport.com)
Bloomberg (www.bloomberg.com)
Bluestem Prairie (www.bluestemprairie.com)
Boston.com
Boston Globe (www.bostonglobe.com)
Boy Genius Report (bgr.com)
Brampton Guardian
Brennan Center for Justice (www.brennancenter.org)
Brookings Institute (www.brookings.edu)
Buffalo News (www.buffalonews.com)
Bulletin of Atomic Scientists (thebulletin.org)
Business Insider (www.businessinsider.com)
Bustle Magazine (www.bustle.com)
Buzzfeed (www.buzzfeed.com)
CalWatchdog.com (calwatchdog.com)
Canadaland (www.canadalandshow.com)
Capital Gazette (www.capitalgazette.com)
Caribbean Life News (www.caribbeanlifenews.com)
Carnegie Endowment for International Peace (carnegieendowment.org)
Carolina Public Press (carolinapublicpress.org)
Catch News (http://www.catchnews.com)
CBC News (www.cbc.ca)
CBS Boston – WBZ-TV (boston.cbslocal.com)
CBS Los Angeles – KCBS (losangeles.cbslocal.com)
CBS News (www.cbsnews.com)
Censor.NET
Center for Advanced Defense studies (c4ads.org)
Center for Global Development (www.cgdev.org)
Center for Inquiry (www.centerforinquiry.org)
Center for International Policy (www.ciponline.org)
Center for a New American Security (www.cnas.org)
Center for Popular Democracy (populardemocracy.org)
Center for Public Integrity (www.publicintegrity.org)
Center on Budget and Policy Priorities (www.cbpp.org)
Central News Agency (CNA) / Focus Taiwan (http://focustaiwan.tw/)
Channel 4 News (UK) (channel4.com/news)
Charleston Gazette Mail (www.wvgazettemail.com)
Charlotte Observer (www.charlotteobserver.com)
Cheddar (cheddar.com)
Chicago Sun-Times (chicago.suntimes.com)
China Africa Project (chinaafricaproject.com)
Citizen Truth (citizentruth.org)
Citizens for Responsibility and Ethics in Washington (CREW) (www.citizensforethics.org)
Citizens for Tax Justice (ctj.org)
CityLab (Citylab.com)
City Pages (citypages.com)
City and State New York (cityandstateny.com)
Clarion Ledger (clarionledger.com)
Clean Technica (cleantechnica.com)
CNBC (www.cnbc.com)
Columbia Journalism Review (www.cjr.org)
Columbia Reports (colombiareports.com)
Columbus Dispatch (www.dispatch.com)
Committee to Investigate Russia (investigaterussia.org)
Common Cause (www.commoncause.org)
Commonweal Magazine (www.commonwealmagazine.org)
CommonWealth fund (www.commonwealthfund.org)
Connecticut Post (ctpost.com)
Consortium News (consortiumnews.com)
Constitution Project (www.constitutionproject.org)
Corpus Christi Caller-Times
CrossCut.com (crosscut.com)
CT Mirror (ctmirror.org)
Daily Hampshire Gazette
Daily Mirror (www.mirror.co.uk)
Daily Nation (nation.africa)
Dawn (www.dawn.com)
DCist (dcist.com)
DCReport.org (www.dcreport.org)
Deadline Hollywood (deadline.com)
Deccan Herald (www.deccanherald.com)
Debunking Denialism (debunkingdenialism.com)
Delaware Online – The News Journal (www.delawareonline.com)
Delo (delo.si)
Democracy 21 (www.democracy21.org)
Democrat and Chronicle (www.democratandchronicle.com)
Demos (www.demos.org)
Denver Post (www.denverpost.com)
Denver Westword
Detroit Free Press (www.freep.com)
Die Zeit (www.zeit.de)
Digg (digg.com)
Diply (https://diply.com/)
DiversityInc (www.diversityinc.com)
Dutch Daily News (www.dutchdailynews.com)
Dutch Review (dutchreview.com)
DW News (www.dw.com)
Earth Institute (earth.columbia.edu)
EarthJustice (earthjustice.org)
East Bay Times (www.eastbaytimes.com)
Econofact
Economic Policy Institute (www.epi.org)
Economics.Help (www.economicshelp.org)
Egyptian Streets (egyptianstreets.com)
El Diario NY (eldiariony.com)
El Pais (elpais.com)
El Paso Times (www.elpasotimes.com)
Electronic Frontier Foundation (www.eff.org)
Emerging Europe (emerging-europe.com)
Empty Wheel (www.emptywheel.net)
Engadget (www.engadget.com)
Entertainment Weekly (https://ew.com)
ESPN (espn.com)
Eugene Register-Guard (registerguard.com)
EU Observer (euobserver.com)
EurActiv (www.euractiv.com)
Eurasia Review (www.eurasiareview.com)
Euromaiden Press
Euronews (www.euronews.com)
Exposing the Truth (www.exposingtruth.com)
Facebook News (facebook.com/news)
Fact/Myth (factmyth.com)
Fairness and Accuracy in Reporting (fair.org)
FairVote (www.fairvote.org)
Fast Company (www.fastcompany.com)
Feminist Frequency (feministfrequency.com)
Fight for the Future (www.fightforthefuture.org)
FivethirtyEight (fivethirtyeight.com)
Foreign Policy in Focus (fpif.org)
Fort Worth Weekly (www.fwweekly.com)
France Info (francetvinfo.fr)
Freakonomics (freakonomics.com)
Fresno Bee (www.fresnobee.com)
Fusion (fusion.net)
Gay Star News (www.gaystarnews.com)
Glamour Magazine (www.glamour.com)
Global Citizen (www.globalcitizen.org)
Global News (globalnews.ca)
Global Post (www.pri.org)
Global Real News (globalrealnews.com)
Global Risk Insights (globalriskinsights.com)
Global Times (www.globaltimes.cn)
Google News
Gothamist (gothamist.com)
Governing Magazine (www.governing.com)
Government Accountability Project (whistleblower.org)
Government Executive (www.govexec.com)
Greensboro News and Record
Greentech Media (www.greentechmedia.com)
Grist (grist.org)
Gun Violence Archive (www.gunviolencearchive.org)
Harpers (harpers.org)
Hartford Courant (www.courant.com)
Harvard Political Review (harvardpolitics.com)
Health Magazine (www.health.com)
HealthyWay (www.healthyway.com)
Heavy (heavy.com)
Helsingin Sanomat (hs.fi)
Helsinki Times (www.helsinkitimes.fi)
High Country News (www.hcn.org)
Highline (highline.huffingtonpost.com)
Hindustan Times (www.hindustantimes.com)
History News Network (historynewsnetwork.org)
Hollywood Reporter (www.hollywoodreporter.com)
Honolulu Civil Beat (civilbeat.org)
Honolulu Star-Advertiser (www.staradvertiser.com)
Houston Chronicle (www.chron.com)
Human Rights Watch (www.hrw.org)
Humanium (www.humanium.org)
Ice News (www.icenews.is)
Idaho Press-Tribune (idahopress.com)
If America Knew (ifamericaknew.org)
IFL Science (www.iflscience.com)
Independent Australia (independentaustralia.net)
iNews (inews.co.uk)
InfoBae (infobae.com)
Inquisitr (www.inquisitr.com)
Inside Edition (www.insideedition.com)
Inside Higher Ed (www.insidehighered.com)
Inside Philanthropy (www.insidephilanthropy.com)
Insider (insider.com)
InsideClimate News (insideclimatenews.org)
Institute for Middle East Understanding (imeu.org)
Institute on Taxation and Economic Policy (ITEP) (itep.org)
International Business Times (www.ibtimes.com)
International Center for Research on Women (www.icrw.org)
International Crisis Group (www.crisisgroup.org)
Interpreter Magazine (www.interpretermag.com)
Inverse (www.inverse.com)
Ipolitics (ipolitics.ca)
The New Humanitarian (thenewhumanitarian.org)
Jackson Free Press (www.jacksonfreepress.com)
Japan Today (www.japantoday.com)
Jihadica (www.jihadica.com)
Joint Center for Polititical and Economic Studies (jointcenter.org)
Journal Politics and Society (www.helvidius.org)
Jstor Daily (daily.jstor.org)
Just Security (www.justsecurity.org)
Kansas City Star (www.kansascity.com)
Kenosha News (kenoshanews.com)
Knight Foundation (www.knightfoundation.org)
KOCO News 5 (www.koco.com)
Kotaku (kotaku.com)
KQED (kqed.org)
KUOW NPR (kuow.org)
Kurdistan 24 (www.kurdistan24.net)
Kyiv Post
Laconia Daily Sun (laconiadailysun.com)
La Presse (www.lapresse.ca)
La Repubblica (repubblica.it)
La Stampa (lastampa.it)
LA Times (www.latimes.com)
Las Vegas Sun (lasvegassun.com)
Latin Times (www.latintimes.com)
Law & Crime (lawandcrime.com)
Leavenworth Times (leavenworthtimes.com)
Left Justified (www.leftjustified.com)
Lethbridge Herald (lethbridgeherald.com)
Lexington Herald Leader (www.kentucky.com)
Liberal Mountain (www.liberalmountain.com)
Lifehacker (lifehacker.com)
Los Angeles Magazine (lamag.com)
Maclean’s Magazine (www.macleans.ca)
Maine Beacon (mainebeacon.com)
Mainichi Shimbun (mainichi.jp)
Malaysiakini
Manila Bulletin (mb.com.ph)
Maplight (maplight.org)
McClatchy DC (www.mcclatchydc.com)
MediaFile (www.mediafiledc.com)
Medium (medium.com)
Metro (www.metro.us)
Metro UK (metro.co.uk)
New Haven Register (nhregister.com)
Mexico Daily News (mexiconewsdaily.com)
Miami Herald (www.miamiherald.com)
MIC (mic.com)
Migration Policy Institute (www.migrationpolicy.org)
Milwaukee Journal-Sentinal (www.jsonline.com)
Minneapolis Star-Tribune (www.startribune.com)
Minnesota Public Radio (MPR) (www.mprnews.org)
MinnPost (www.minnpost.com)
Mint Press News (www.mintpressnews.com)
Mongabay (news.mongabay.com)
Moscow Times (themoscowtimes.com)
Mother Jones (www.motherjones.com)
Mother Nature Network (www.mnn.com)
Mothership
MSN.com (www.msn.com)
Muncie Voice (www.muncievoice.com)
MWC News – Media With Conscience (mwcnews.net)
MyCentralJersey.com
Naked Capitalism (www.nakedcapitalism.com)
Naples Daily News (www.naplesnews.com)
National Center for Transgender Equality (transequality.org)
National Monitor (natmonitor.com)
National Newswatch (www.nationalnewswatch.com)
National Observer (www.nationalobserver.com)
National Youth Right Association (www.youthrights.org)
Natural Resource Governance Institute (www.resourcegovernance.org)
Nature Conservancy (www.nature.org)
NBC Los Angeles – KNBC (nbclosangeles.com)
NBC News (www.nbcnews.com)
NBCNewYork.com (nbcnewyork.com)
NDTV (www.ndtv.com)
New America Foundation (www.newamerica.org)
New England Cable News (NECN) (www.necn.com)
New Castle News (ncnewsonline.com)
New Europe (www.neweurope.eu)
New Left Review (newleftreview.org)
New Matilda (newmatilda.com)
New Moderate (newmoderate.com)
News1130 & City News (citynews1130.com)
NewsCenterMaine.com
New York Daily News (www.nydailynews.com)
New York Times (www.nytimes.com)
News and Guts (www.newsandgutsmedia.com)
News Deeply (www.newsdeeply.com)
Newsday (www.newsday.com)
Newser (www.newser.com)
Newsweek (www.newsweek.com)
Newsy (www.newsy.com)
NHK World (nhk.or.jp/nhkworld/)
Novinky.cz
NPR (www.npr.org)
Occupy Independents (occupyindependents.com)
OCWeekly (www.ocweekly.com)
Oil and Water Don’t Mix (www.oilandwaterdontmix.org)
OneIndia (www.oneindia.com)
openDemocracy (www.opendemocracy.net)
Open the Government (www.openthegovernment.org)
Opposing Views (www.opposingviews.com)
Orlando Sentinel (www.orlandosentinel.com)
Our World In Data (ourworldindata.org)
Outside The Beltway (www.outsidethebeltway.com)
Ozy Media (www.ozy.com)
Pacific Standard Magazine (psmag.com)
Palm Beach Daily News (palmbeachdailynews.com)
Patriotic Millionaires (patrioticmillionaires.org)
PBS News Hour (www.pbs.org)
Philadelphia Inquirer (inquirer.com)
Philadelphia Tribune
Philippine Daily Inquirer (www.inquirer.net)
Philly Voice (phillyvoice.com)
Phoenix News Times (www.phoenixnewtimes.com)
Political Critique (politicalcritique.org)
Politico (www.politico.com)
Politics That Work (politicsthatwork.com)
Politifact (www.politifact.com)
Polygon (polygon.com)
Population Connection (www.populationconnection.org)
Portland Press-Herald (www.pressherald.com)
Portland Tribune (pamplinmedia.com)
Positive News (www.positive.news)
PRI
Private Eye (www.private-eye.co.uk)
Project on Government Insight (pogo.org)
Project Syndicate (www.project-syndicate.org)
Propublica (www.propublica.org)
Prospect Magazine (www.prospectmagazine.co.uk)
Providence Journal (www.providencejournal.com)
Public Citizen (www.citizen.org)
Quartz (qz.com)
Radio Free Asia (www.rfa.org)
Raleigh News & Observer (www.newsobserver.com)
RationalWiki (rationalwiki.org)
Religion News Service (religionnews.com)
Reno Gazette Journal (https://www.rgj.com)
Represent.us (represent.us)
Reveal (www.revealnews.org)
Right Web (rightweb.irc-online.org)
RocketNews (rocketnews.com)
Rock Hill Herald (heraldonline.com)
Roosevelt Institute (rooseveltinstitute.org)
Sacramento Bee (www.sacbee.com)
Salt Lake Tribune (www.sltrib.com)
San Antonio Express (www.mysanantonio.com)
San Diego Reader (www.sandiegoreader.com)
San Francisco Chronicle (www.sfchronicle.com)
San Francisco Examiner (www.sfexaminer.com)
San Francisco Globe (sfglobe.com)
San Jose Mercury News (www.mercurynews.com)
San Luis Obispo Tribune (sanluisobispo.com)
Santa Barbara Independent (www.independent.com)
Sapiens (sapiens.org)
Saudi Gazette (saudigazette.com.sa)
Sciencing (sciencing.com)
ScoopWhoop (www.scoopwhoop.com)
Scroll.in (scroll.in)
Seattle Post-Intelligencer (www.seattlepi.com)
Seattle Times (www.seattletimes.com)
Sentencing Project (www.sentencingproject.org)
SFGate (www.sfgate.com)
Shame Project (shameproject.com)
Sojourners (sojo.net)
SooToday.com (www.sootoday.com)
South China Morning Post (www.scmp.com)
Special Broadcasting Service (www.sbs.com.au)
Spiegel Online (www.spiegel.de)
St. Louis Post-Dispatch
St. Paul Pioneer Press (www.twincities.com)
Stamford Advocate (stamfordadvocate.com)
Star Ledger (www.nj.com)
STAT (News) (www.statnews.com)
Stepfeed (stepfeed.com)
Stop Fake (www.stopfake.org)
Stuff (www.stuff.co.nz)
Sunlight Foundation (sunlightfoundation.com)
SWI – Swissinfo.ch (www.swissinfo.ch)
Syrian Observatory for Human Rights (SOHR)
Tablet Magazine (www.tabletmag.com)
Taiwan News (www.taiwannews.com.tw)
Tampa Bay Times (www.tampabay.com)
Tarbell (www.tarbell.org)
Tax Justice Network (www.taxjustice.net)
Tax Policy Center (www.taxpolicycenter.org)
TechCrunch (techcrunch.com)
Techdirt (www.techdirt.com)
Texas Monthly (www.texasmonthly.com)
Texas Tribune (www.texastribune.org)
The Age (Australia) (www.theage.com.au)
The Asahi Shimbun (www.asahi.com)
The Asbury Park Press
The Automatic Earth (www.theautomaticearth.com)
The Baffler (thebaffler.com)
The Bipartisan Press
The Brownsville Herald
The Budapest Beacon (budapestbeacon.com)
The Bureau of Investigative Journalism (www.thebureauinvestigates.com)
The Center for Economic Policy and Research (CEPR)
The Century Foundation (tcf.org)
The China Post (chinapost.nownews.com)
The Christian Left (www.thechristianleft.org)
The Chronicle of Higher Education (www.chronicle.com)
The Citizen (www.thecitizen.org.au)
The City (thecity.nyc)
The Colorado Sun (coloradosun.com)
The Council of Canadians (canadians.org)
The Courier-Journal (www.courier-journal.com)
The Daily Climate (www.dailyclimate.org)
The Daily Hive (dailyhive.com)
The Daily Tarheel (www.dailytarheel.com)
The Dominion Post (dominionpost.com)
The European Council on Foreign Relations (ECFR) (www.ecfr.eu)
The Express-Times (Lehigh Valley) (www.lehighvalleylive.com)
The Forward (forward.com)
The Frontier (https://www.readfrontier.org)
The Fulcrum (thefulcrum.us)
The Guardian (www.theguardian.com)
The Herald (Everett) (www.heraldnet.com)
The Hill Talk (thehilltalk.com)
The Hindu (newsite.thehindu.com)
The Humanist Magazine (thehumanist.com)
The Independent (www.independent.co.uk)
The Indian Express (indianexpress.com)
The Intercept (theintercept.com)
The Irish Times (www.irishtimes.com)
The Irrawaddy (www.irrawaddy.com)
The Jakarta Post (www.thejakartapost.com)
TheJournal.ie (www.thejournal.ie)
The Journal News (www.lohud.com)
The Korea Times (www.koreatimes.co.kr)
The Lincoln Project (lincolnproject.us)
The List (thelist.com)
The Local (Norway) (www.thelocal.no)
The Maui News (mauinews.com)
The Moderate Voice (themoderatevoice.com)
The Motley Fool (fool.com)
The New Arab (www.alaraby.co.uk)
The New Tropic (thenewtropic.com)
The News Tribune (www.thenewstribune.com)
The News-Times (Danbury) (www.newstimes.com)
The Next Web (TNW) (thenextweb.com)
The Observer (UK)
The Odyssey Online (www.theodysseyonline.com)
The Olympian (www.theolympian.com)
The Palm Beach Post (www.palmbeachpost.com)
The Patriot-News (www.pennlive.com)
The Plain Dealer (www.cleveland.com)
The Press Democrat (www.pressdemocrat.com)
The Pulse (pulsegulfcoast.com)
The Record (New Jersey) (www.northjersey.com)
The Ringer (www.theringer.com)
The Santa Fe New Mexican
The Saturday Paper (www.thesaturdaypaper.com.au)
The Skimm (www.theskimm.com)
The State (www.thestate.com)
The State Press (Arizona) (statepress.com)
The Sun Magazine (thesunmagazine.org)
The Sydney Morning Herald (www.smh.com.au)
The Tab (thetab.com)
The Trace (www.thetrace.org)
The Tyee (thetyee.ca)
The Varsity (thevarsity.ca)
The Verge (www.theverge.com)
The Virginian-Pilot (pilotonline.com)
The Week UK (www.theweek.co.uk)
The Wilderness Society (wilderness.org)
The Wire – India (thewire.in)
TheWrap (www.thewrap.com)
Thomson Reuters Foundation (news.trust.org)
Thrillist (https://www.thrillist.com)
Time Magazine (time.com)
Timeline
Times Colonist
Times Headline (www.timesheadline.com)
Times of Israel (www.timesofisrael.com)
Times-Picayune (www.nola.com)
TMZ (https://www.tmz.com/)
Today.com
Tomdispatch.com (www.tomdispatch.com)
Toronto Star (www.thestar.com)
Truth Be Told (truthbetold.news)
Type Media Center (typemediacenter.org)
UAWire (uawire.org)
Union of Concerned Scientists (www.ucsusa.org)
United Federation of Teachers (www.uft.org)
University Business (www.universitybusiness.com)
Ukrayinska Pravda (The Ukrainian Truth) (pravda.com.ua)
Urban Institute (www.urban.org)
USA Today (www.usatoday.com)
UsNews and World Report (www.usnews.com)
Utah Public Radio (UTR) (upr.org)
Utica Observer-Dispatch (uticaod.com)
Variety Magazine (variety.com)
Vibe (vibe.com)
Vice News (www.vice.com)
Victoria Advocate (victoriaadvocate.com)
Virginia Mercury (virginiamercury.com)
Voice of San Diego (www.voiceofsandiego.org)
Vote Vets (www.votevets.org)
Vulture (www.vulture.com)
WalesOnline (walesonline.co.uk)
WAMU-FM (WAMU.org)
Washington Blade (www.washingtonblade.com)
Washington Monthly (washingtonmonthly.com)
Washington Post (www.washingtonpost.com)
Western Mass News (westernmassnews.com)
Whitehouse.gov (whitehouse.gov)
Wikileaks (www.wikileaks.org)
Wired Magazine (www.wired.com)
WNYC (www.wnyc.org)
Woodrow Wilson International Center (www.wilsoncenter.org)
World Policy Institute (www.worldpolicy.org)
WorldCrunch (www.worldcrunch.com)
World Press Review (worldpress.org)
WSVN (wsvn.com)
Xinhua News Agency (www.news.cn)
Yahoo News (news.yahoo.com)
YaleGlobal Online (https://yaleglobal.yale.edu/)
YnetNews (www.ynetnews.com)
York Daily Record (www.ydr.com)
York Dispatch (www.yorkdispatch.com)
Youth Radio (youthradio.org)
