2ndVote (2ndvote.com)
Abort73
Accuracy in Academia (AIA) (www.academia.org)
Accuracy in Media (www.aim.org)
Against Crony Capitalism (www.ac2news.com)
AltNewsMedia.net (altnewsmedia.net)
AMAC (Association of Mature American Citizens) (https://amac.us/)
America First Action SuperPAC
America Rising PAC (https://americarisingpac.org/)
American Center for Law & Justice (ACLJ) (aclj.org)
American Consequences (americanconsequences.com)
American Enterprise Institute (www.aei.org)
American for Prosperity (americansforprosperity.org)
American Foreign Policy council (www.afpc.org)
American Greatness (amgreatness.com)
American Legislative Exchange Council (ALEC) (www.alec.org)
American Liberty Report (www.americanlibertyreport.com)
American Spectator (spectator.org)
Ami Magazine (amimagazine.org)
Ammoland (www.ammoland.com)
Anadolu Agency (www.aa.com.tr)
Arizona Daily Independent (arizonadailyindependent.com)
Armstrong Economics (www.armstrongeconomics.com)
AsianNews.it
Assyrian International News Agency (www.aina.org)
Axiom News Network (axiomnewsnetwork.com)
Badger Institute
Bearing Arms (bearingarms.com)
Beliefnet (www.beliefnet.com)
BizPac Review (www.bizpacreview.com)
Blabber Buzz (blabber.buzz)
Blue Lives Matter (bluelivesmatter.blue)
Bounding Into Comics (boundingintocomics.com)
BrexitCentral (brexitcentral.com)
Buzzsaw Politics (buzzsawpolitics.com)
C2C Journal (c2cjournal.ca)
Calgary Sun (www.calgarysun.com)
Cambridge Analytica (ca-political.com)
Campign Life Coalition (www.campaignlifecoalition.com)
Campus Reform (www.campusreform.org)
Capital Research Center (capitalresearch.org)
Center for Freedom and Prosperity
Chicks on the Right (www.chicksontheright.com)
Christian Coalition of America (http://www.cc.org)
Christian Headlines (christianheadlines.com)
Christian News Alert (www.christiannewsalerts.com)
Christian Post (www.christianpost.com)
Christian Today (christiantoday.com)
Chronicles Magazine (www.chroniclesmagazine.org)
Citizen Free Press (www.citizenfreepress.com)
Citizens United (citizensunited.org)
City Journal (www.city-journal.org)
Civitas Institute (www.nccivitas.org)
Claremont Institute (claremont.org)
Cold Dead Hands (www.colddeadhands.us)
Commentary Magazine (www.commentarymagazine.com)
Communities Digital News (www.commdiginews.com)
Conservative Base (conservativebase.com)
Conservative HQ (www.conservativehq.com)
Conservative Institute (www.conservativeinstitute.org)
Conservative Opinion (conservativeopinion.com)
Conservative Review (www.conservativereview.com)
Conservative Today (conservativetoday.com)
Cowger Nation (cowgernation.com)
Crime Prevention Research Center (crimeresearch.org)
Crisis Magazine (www.crisismagazine.com)
Daily Caller (dailycaller.com)
Daily Express (www.express.co.uk)
Daily Liberator (www.thedailyliberator.com)
Daily Signal (dailysignal.com)
Daily Telegraph (UK) (www.telegraph.co.uk)
DC Statesman (www.dcstatesman.com)
Daily Torch (dailytorch.com/)
DC Whispers (dcwhispers.com)
De Telegraaf (telegraaf.nl)
Disrn (disrn.com)
DML News (dmlnews.com)
DonaldJTrump.com
Eagle PAC (eagleactionreport.com)
Eagle Pass News Leader
EconomicPolicyJournal.com (www.economicpolicyjournal.com)
Egypt Today (https://www.egypttoday.com)
Energy Citizens (energycitizens.org)
Ethics & Religious Liberty Commission (erlc.com)
Facts and Logic about the Middle East (factsandlogic.org)
FaithWire (www.faithwire.com)
Fake Hate Crimes (fakehatecrimes.org)
Far Left Watch (farleftwatch.com)
Federalist Press (federalistpress.com)
Federalist Society (fedsoc.org)
First in Freedom Daily (firstinfreedomdaily.com)
First Things Magazine (www.firstthings.com)
Foundation for Defense of Democracies (www.defenddemocracy.org)
Fox News (www.foxnews.com)
Free Republic (www.freerepublic.com)
Freedom Cross Roads (freedomcrossroads.com/)
FreedomWorks (www.freedomworks.org)
Frontiers of Freedom (www.ff.org)
Future in America (www.futureinamerica.com)
Get Religion (www.getreligion.org)
GOPUSA (www.gopusa.com)
Government Accountablity Institute (www.g-a-i.org)
Grabien News (news.grabien.com)
Great American Politics (greatamericanpolitics.com)
Guido Fawkes (order-order.com)
Heritage Foundation (www.heritage.org)
HermanCain.com (www.hermancain.com)
Hot Air (hotair.com)
Hudson Institute (www.hudson.org)
Human Events (humanevents.com)
Hurriyet (hurriyet.com.tr)
Hurriyet Daily News (www.hurriyetdailynews.com)
I Bleed Red White and Blue (ibleedredwhiteblue.com)
Illinois Policy Institute (www.illinoispolicy.org)
Imprimis (imprimis.hillsdale.edu)
Independent Women’s Forum (iwf.org)
Influence Watch (www.influencewatch.org)
Institute for Family Studies (ifstudies.org)
Intellectual Takeout (www.intellectualtakeout.org)
Investors Business Daily (www.investors.com)
iPatriot (ipatriot.com)
Israel Hayom (www.israelhayom.com)
Issues & Insights (issuesinsights.com)
Jewish Policy Center (www.jewishpolicycenter.org)
Jewish World Review (www.jewishworldreview.com)
Judicial Crisis Network (judicialnetwork.com)
Just the News (justthenews.com)
Kansas Policy Institute (kansaspolicy.org)
Law Enforcement Today (lawenforcementtoday.com)
Legal Insurrection (legalinsurrection.com)
Liberty Headlines (www.libertyheadlines.com)
Liberty Nation (www.libertynation.com)
Life Decisions International (fightpp.org)
Lifezette (www.lifezette.com)
Lone Conservative (loneconservative.com)
Lozier Institute (lozierinstitute.org)
Manhattan Institute for Policy Research (www.manhattan-institute.org)
Media Circus (www.mediacircus.com)
Media Equalizer (mediaequalizer.com)
Media Research Center (MRC (www.mrc.org)
Mercatornet (www.mercatornet.com)
Milliyet (milliyet.com.tr/)
Minnesota Sun (theminnesotasun.com)
Mises Institute (mises.org)
National Center for Public Policy Research (www.nationalcenter.org)
National Review (www.nationalreview.com)
New Boston Post (newbostonpost.com)
Newsbusters (www.newsbusters.org)
NRA – Institute for Legislative Action (www.nraila.org)
NTK Network (ntknetwork.com)
Numbers USA (www.numbersusa.com)
Offgrid Survival (offgridsurvival.com)
One Angry Gamer (oneangrygamer.net)
OneNewsNow (www.onenewsnow.com)
Ontario Proud (www.ontarioproud.ca)
OpsLens (www.opslens.com)
PanAm Post (panampost.com)
Pants of Fire News (pantsonfirenews.com)
Patriot News Alerts (www.patriotnewsalerts.com)
Patriot News Daily (patriotnewsdaily.com)
PatriotRetort.com (patriotretort.com)
Pluralist (www.pluralist.com)
Politicalite (politicalite.com)
Politichicks (politichicks.com)
Politifeed (politifeed.net)
Populist Wire (www.populistwire.com)
Powerline (www.powerlineblog.com)
Proud Conservative (conservativesus.party)
Public Interest Legal Foundation (publicinterestlegal.org)
Quadrant Magazine (quadrant.org.au)
Reader’s Digest (www.rd.com)
Red Alert Politics (redalertpolitics.com)
Regated News
RenewedRight.com (renewedright.com)
Restore American Glory (www.restoreamericanglory.com)
Richochet (ricochet.com)
Right & Free (rightandfree.com)
Ron Paul Liberty Report (www.ronpaullibertyreport.com)
Sabah (sabah.com.tr)
Save Jersey (savejersey.com)
Sentinel KSMO (sentinelksmo.org)
SharylAttkisson.com
Sinclair Broadcast Group (sbgi.net)
Sky News Australia (skynews.com.au)
Sonoran News (sonorannews.com)
Southern Patriot News (southernpatriotnews.com)
Spiked Magazine (spiked-online.com)
StandPoint (www.standpointmag.co.uk)
Star Political (starpolitical.com/)
Tenth Amendment Center (tenthamendmentcenter.com)
The Advertiser (www.adelaidenow.com.au)
The American Mind (americanmind.org)
The Citizen Press (thecitizenpress.com)
The College Fix (www.thecollegefix.com)
The Conservative Nut (www.theconservativenut.gop)
The Conservative Opinion
The Conservative Woman (www.conservativewoman.co.uk)
The Daily Defender (thedailydefender.com)
The Daily Telegraph (AUS) (www.dailytelegraph.com.au)
The DC Chronicle (dc-chronicle.com)
The First TV (thefirsttv.com)
TheGreggJarrett.com
The Hayride (thehayride.com)
Thejeffreylord.com
The Liberty Loft (thelibertyloft.com)
The National Herald (thenationalherald.com)
The New American (www.thenewamerican.com)
The New Revere (thenewrevere.com)
The Ohio Star (theohiostar.com)
The Patriot Post (patriotpost.us)
The Post Millennial (www.thepostmillennial.com)
Punching Bag Post (punchingbagpost.com)
The RANTidote (therantidote.com)
The Rebel News (rebelnews.com)
The Resurgent (theresurgent.com)
The Ron Paul Institute (www.ronpaulinstitute.org)
The Star (Malaysia) (thestar.com.my)
The Sun (www.thesun.co.uk)
The Tennessee Star (tennesseestar.com)
The Truth About Guns (www.thetruthaboutguns.com)
Toronto Sun (www.torontosun.com)
Trending Views (trendingviews.co)
Tribunist (tribunist.com)
TRT World (www.trtworld.com)
Twitchy (twitchy.com)
UN Watch (www.unwatch.org)
Unity News Network (unitynewsnetwork.co.uk)
Update America (https://www.updateamerica.com/)
Viva Liberty (www.vivaliberty.com)
Washington Examiner (www.washingtonexaminer.com)
Washington Free Beacon (freebeacon.com)
Weasel Zippers (www.weaselzippers.us)
Weekly Standard (www.weeklystandard.com)
Western Free Press (www.westernfreepress.com)
WestMonster (www.westmonster.com)
Whatfinger (www.whatfinger.com)
World Magazine (world.wng.org)
World Tribune (worldtribune.com)
Yellow Hammer News (yellowhammernews.com)
Young Americas Foundation (YAF) (www.yaf.org)
Young Conservatives (www.youngcons.com)
