7NEWS (7news.com.au)
9 News (Australia) (www.9news.com.au)
ABC (Spain) (abc.es)
Advocates for Self-Government (theadvocates.org)
Ahram Online (english.ahram.org.eg)
Al.com (Alabama News) (www.al.com)
Albuquerque Journal (www.abqjournal.com)
Aleteia
American Action Forum (www.americanactionforum.org)
American Affairs Journal (americanaffairsjournal.org)
American Council on Science and Health (ACSH) (acsh.org)
American Firearms Institute (www.americanfirearms.org)
American Institute for Economic Research (aier.org)
Americas Quarterly (www.americasquarterly.org)
Angus Reid Institute
Anti-War (antiwar.com)
ArcaMax (arcamax.com)
Argus Leader
Arkansas Democrat-Gazette (www.arkansasonline.com)
Arutz Sheva (Israel National News) (www.israelnationalnews.com)
Asharq Al-Awsat
Asian News International (www.aninews.in)
Atlantic Council (www.atlanticcouncil.org)
Barron’s
Being Libertarian (beinglibertarian.com)
Berlingske (berlingske.dk)
Bild (bild.de)
Billings Gazette (billingsgazette.com)
Bipartisan Policy Center (bipartisanpolicy.org)
Boston Herald (www.bostonherald.com)
Breaking Defense (breakingdefense.com)
Breakthrough Institute (thebreakthrough.org)
B.T. Denmark (bt.dk)
Buenos Aires Times
BusinessLIVE (www.businesslive.co.za)
Calgary Herald (calgaryherald.com)
California Globe (https://californiaglobe.com/)
California Political Review (www.capoliticalreview.com)
Campaign for Liberty (campaignforliberty.org)
Canadian Jewish News (www.cjnews.com)
Canadian Taxpayers Federation (www.taxpayer.com)
Capitalism Magazine (capitalismmagazine.com)
Cato Institute (www.cato.org)
CCN (https://www.ccn.com)
Center for the National Interest (cftni.org)
Check Your Fact (checkyourfact.com)
Chicago Tribune (www.chicagotribune.com)
Christianity Today (www.christianitytoday.com)
Colorado Springs Gazette (gazette.com)
Columbia Daily Herald (www.columbiadailyherald.com)
Committee for a Responsible Federal Buddget (crfb.org)
Daily Herald (www.dailyherald.com)
Daily Mining Gazette (mininggazette.com)
Daily Press (www.dailypress.com)
DailyO (https://www.dailyo.in)
Dallas Morning News (www.dallasnews.com)
de Volkskrant (www.volkskrant.nl)
Deccan Chronicle (www.deccanchronicle.com)
Denver Gazette (denvergazette.com)
Deseret News (www.deseretnews.com)
Desert Sun (www.desertsun.com)
Detroit News (www.detroitnews.com)
Deutschland.de
Die Presse (diepresse.com)
Die Welt (welt.de)
Downsizing the Federal Government (www.downsizinggovernment.org)
Drudge Report (www.drudgereport.com)
Ecuavisa (ecuavisa.com)
Edmonton Examiner (edmontonexaminer.com)
Edmonton Journal (edmontonjournal.com)
Edmonton Sun (www.edmontonsun.com)
El Mundo (elmundo.es)
Ethics and Public Policy Center (EPPC) (eppc.org)
Ethnikos Kyrix (ekirikas.com)
Expressen (expressen.se)
Faith Family America (www.faithfamilyamerica.com)
FDD’s Long War Journal (longwarjournal.org)
Financial Express (www.financialexpress.com)
Financial Post (www.financialpost.com)
Firearms News
First Post (www.firstpost.com)
Fitch Ratings (fitchratings.com)
FitsNews (www.fitsnews.com)
Forbes (www.forbes.com)
Foreign Policy Research Institute (www.fpri.org)
Fort Bend Herald
Fort Worth Star-Telegram (www.star-telegram.com)
Fortnightly Review (fortnightlyreview.co.uk)
Fortune Magazine (fortune.com)
Foundation for Economic Education (fee.org)
Fox Business (foxbusiness.com)
Franklin News Foundation (franklinnews.org)
Fraser Institute (www.fraserinstitute.org)
Freedom Alliance (https://freedomalliance.org)
Freedom House (freedomhouse.org)
Göteborgs-Posten (gp.se)
Grand Rapids Press (www.mlive.com)
Greeley Tribune
Guns.com (www.guns.com)
Herald Sun (AUS) (www.heraldsun.com.au)
Heterodox Academy (heterodoxacademy.org)
Het Laatste Nieuws (HLN) (hln.be)
High Point Enterprise (www.hpenews.com)
Hindu Business Line (www.thehindubusinessline.com)
Honest Reporting (honestreporting.com)
Hoover Institution (www.hoover.org)
Human Progress (humanprogress.org)
Idaho State Journal (idahostatejournal.com)
iefimerida.gr
Il Giornale (ilgiornale.it)
In Homeland Security (inhomelandsecurity.com)
India.com
India Times (www.indiatimes.com/)
India Today (indiatoday.in)
Inforum (The Forum of Fargo-Moorhead) (https://www.inforum.com)
InsideSources (www.insidesources.com)
Institute for Humane Studies (theihs.org)
Irish Independent (www.independent.ie)
ITV News (www.itv.com)
Jerusalem Post (www.jpost.com)
Jewish Breaking News (jewishbreakingnews.com)
Jewish Journal (jewishjournal.com)
Jewish News Syndicate (www.jns.org)
Just Facts (www.justfacts.com)
Just Facts Daily (www.justfactsdaily.com)
KATU2 (katu.com)
Knewz (knewz.com)
Korean Herald (www.koreaherald.com)
KUTV Salt Lake City (kutv.com)
Laredo Morning Times (https://www.lmtonline.com)
Las Vegas Review Journal (www.reviewjournal.com)
Learn Liberty (www.learnliberty.org)
Leicester Mercury (leicestermercury.co.uk)
Lexington Institute (lexingtoninstitute.org)
Libertarianism.org (www.libertarianism.org)
ListVerse (listverse.com)
London Broadcasting Company (LBC) (www.lbc.co.uk)
London Evening Standard (www.standard.co.uk)
London Free Press (www.lfpress.com)
Los Angeles Daily News (www.dailynews.com)
Lubbock Avalanche Journal
Lynx Media (lynx.media)
Mackinac Center for Public Policy (www.mackinac.org)
Malaysia Today
Manchester Union leader (www.unionleader.com)
Manila Times (www.manilatimes.net)
Marginal Revolution (marginalrevolution.com)
MarketWatch (www.marketwatch.com)
Mercatus (www.mercatus.org)
Metabunk (www.metabunk.org)
Montreal Gazette (montrealgazette.com)
Mountain Democrat (www.mtdemocrat.com)
MyNorthwest (mynorthwest.com)
National Affairs (www.nationalaffairs.com)
National Interest (nationalinterest.org)
National Post (www.nationalpost.com)
Netherlands Radio and Television Association (nos.nl)
New York Observer (observer.com)
New York Post (nypost.com)
News.com.au (.news.com.au)
News-Gazette (www.news-gazette.com)
NHK-Nippon Hoso Kyokai (nhk.or.jp)
Nikkei Asian Review
NJ1015.com
Northwest Arkansas Democrat-Gazette (nwaonline.com)
Odessa American
Omaha World Herald
Open Doors (www.opendoorsusa.org)
Orange County Register (www.ocregister.com)
Oregonian (www.oregonlive.com)
Ottawa Citizen (ottawacitizen.com)
Ottawa Sun (ottawasun.com)
Pacific Research Institute (www.pacificresearch.org)
Peninsula Daily News (www.peninsuladailynews.com)
Pittsburgh Post-Gazette (www.post-gazette.com)
Pittsburgh Tribune Review (triblive.com)
PolicyEd.org (www.policyed.org)
Politisite (politisite.com)
Post-Bulletin
R Street Institute (www.rstreet.org)
Rasmussen Reports (www.rasmussenreports.com)
Real Clear Defense (www.realcleardefense.com)
Real Clear Investigations (www.realclearinvestigations.com)
Real Clear Policy (www.realclearpolicy.com)
Real Clear Politics (www.realclearpolitics.com)
RealClearReligion (www.realclearreligion.org)
Reason (reason.com)
Red River Valley News (www.valleynewslive.com)
Regina Leader-Post (leaderpost.com)
Regulation Magazine
Remington Research Group (remingtonresearchgroup.com)
Republic World (www.republicworld.com)
Richmond Times-Dispatch
Salem Radio Network News (www.srnnews.com)
San Bernadino Sun (www.sbsun.com)
Saskatoon StarPhoenix (thestarphoenix.com)
Savannah Morning News (savannahnow.com)
Scope Ratings (scoperatings.com)
SOFREP (sofrep.com)
Student Daily News (www.studentnewsdaily.com)
Tallahasee Democrat (www.tallahassee.com)
Tax Foundation (taxfoundation.org)
Tharawat Magazine (www.tharawat-magazine.com)
The Algemeiner Journal (www.algemeiner.com)
The American Conservative (www.theamericanconservative.com)
The American Interest (www.the-american-interest.com)
The Augusta Chronicle (chronicle.augusta.com)
The Australian (www.theaustralian.com.au)
The Bulwark (https://thebulwark.com/)
The Chronicle Herald (thechronicleherald.ca)
The Citizen
The Courier Mail (www.couriermail.com.au)
The Daily Citizen (Dalton)
The Dispatch (thedispatch.com)
The Durango Herald (durangoherald.com)
The EC Journal (www.theecjournal.com)
The Elkhart Truth
The Fiscal Times (www.thefiscaltimes.com)
The Gazette (Cedar Rapids) (www.thegazette.com)
The Globe and Mail (Toronto) (www.theglobeandmail.com)
The Independent Institute (www.independent.org)
The Jack News (www.thejacknews.com)
The Japan News (the-japan-news.com)
The Jerusalem Report
The Jewish Press (www.jewishpress.com)
The Ledger (www.theledger.com)
The Libertarian Republic (thelibertarianrepublic.com)
The Nation Pakistan (nation.com.pk)
The New Atlantis (www.thenewatlantis.com)
The News Lens (international.thenewslens.com)
The Objective Standard (www.theobjectivestandard.com)
The Oklahoman (www.oklahoman.com)
The Post-Journal (Jamestown, New York) (post-journal.com)
The Press-Enterprise (www.pe.com)
The Quint (www.thequint.com)
The Sorrentino (www.thesorrentino.com)
The Spectator (uk) (www.spectator.co.uk)
The Spectator (USA) (spectator.us)
The Spokesman-Review (www.spokesman.com)
The Standard (Kenya) (standardmedia.co.ke)
The Straits Times (www.straitstimes.com)
TheStreet (thestreet.com)
The Sumter Item (www.theitem.com)
The Times Herald (Port Huron) (www.thetimesherald.com)
The Times of India (timesofindia.indiatimes.com)
The Times UK and Sunday Times (www.thetimes.co.uk)
The Washington Institute for Near East Policy (www.washingtoninstitute.org)
The West Australian (thewest.com.au)
The Winchester Star
The Yomiuri Shimbun (yomiuri.co.jp)
Times News (Pennsylvania) (www.tnonline.com)
Times of South Africa (www.timeslive.co.za)
Toledo Blade (www.toledoblade.com)
Topeka Capital-Journal (www.cjonline.com)
To Vima (tovima.gr)
TRIBUNnews.com
Tulsa World
ValueWalk (www.valuewalk.com)
Vancouver Sun (vancouversun.com)
Wall Street Journal (www.wsj.com)
Watchdog.org
Waterbury Republican-American (www.rep-am.com)
West Central Tribune (wctrib.com)
Wichita Eagle (www.kansas.com)
Williamsport Sun-Gazette (www.sungazette.com)
Willoughby News-Herald (news-herald.com)
Windsor Star (windsorstar.com)
WLOS (ABC13News) (wlos.com)
WPEC – CBS12.com (cbs12.com)
Yankee Institute for Public Policy (https://yankeeinstitute.org)
Zebra Fact Check (www.zebrafactcheck.com)
